### ISSUE TITLE
Failures on test suite on a fresh clone on KeysAndPermissionsTest class

### ISSUE THREAD

**Issue by ppshobi** [meilisearch/meilisearch-php#12]
Hi, thanks for the awesome library, I was slowly trying to contribute to the library and did a clone and installed the dependencies. But on the first test suite run, I got the following errors

```
1) KeysAndPermissionsTest::testExceptionIfNoMasterKeyProvided
Failed asserting that exception of type "MeiliSearch\Exceptions\HTTPRequestException" is thrown.

2) KeysAndPermissionsTest::testExceptionIfBadKeyProvidedToGetSettings
Failed asserting that exception of type "MeiliSearch\Exceptions\HTTPRequestException" is thrown.

3) KeysAndPermissionsTest::testExceptionIfBadKeyProvidedToGetKeys
Failed asserting that exception of type "MeiliSearch\Exceptions\HTTPRequestException" is thrown.
```
Any idea on these failures?, I have PHP 7.4 running

**Comment by curquiza** [comment]
Hello!
Thanks for your feedback! Glad to read you want to contribute 😁

Weird, I use php 7.4 too:
```bash
$> php -v
PHP 7.4.5 (cli) (built: Apr 18 2020 03:17:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies
```

What do you run exactly as commands?

I ran exactly the same commands than in the README:
```
$ docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --master-key=masterKey --no-analytics=true
$ vendor/bin/phpunit --color tests/
```

**Comment by ppshobi** [comment]
This is what I run on the terminal. 

```vendor/bin/phpunit --color tests/
PHPUnit 8.5.3 by Sebastian Bergmann and contributors.

.........................................FFF..................... 65 / 75 ( 86%)
..........                                                        75 / 75 (100%)

Time: 1.31 seconds, Memory: 8.00 MB

There were 3 failures:

1) KeysAndPermissionsTest::testExceptionIfNoMasterKeyProvided
Failed asserting that exception of type "MeiliSearch\Exceptions\HTTPRequestException" is thrown.

2) KeysAndPermissionsTest::testExceptionIfBadKeyProvidedToGetSettings
Failed asserting that exception of type "MeiliSearch\Exceptions\HTTPRequestException" is thrown.

3) KeysAndPermissionsTest::testExceptionIfBadKeyProvidedToGetKeys
Failed asserting that exception of type "MeiliSearch\Exceptions\HTTPRequestException" is thrown.

FAILURES!
Tests: 75, Assertions: 260, Failures: 3.
```

**Comment by ppshobi** [comment]
Just made a PR with some changes, and the CI went fine.

**Comment by curquiza** [comment]
Ok! Don't know why then... 😅
Thanks a lot!

**Comment by curquiza** [comment]
Closed with #13

**Comment by ppshobi** [comment]
Actually I have this issue is still with me. The tests are not failing on CI when I was making the PR, but it fails for me in the local. 

Actually here https://github.com/meilisearch/meilisearch-php/blob/972760ca49473fb41476982adca434a902cfe644/src/HTTPRequest.php#L94

The request gets succeeded even if the key is not passed at all. I have downloaded the latest docker image of meilisearch and ran it. 

I have PHP 7.3.13 in another system and still, 3 tests I have mentioned is failing for me.

**Comment by curquiza** [comment]
Ok, sorry I didn't get you still have this issue!

Complicated to investigate it, because I do not succeed to reproduce your issue.

Are you sure you run MeiliSearch with the `--master-key=masterKey` locally?

**Comment by ppshobi** [comment]
yes. And I believe the issue comes with the static methods and properties we have on the test classes. When I run with Xdebug, I can see the `api_key` being passed to the client. And generally, I tend to avoid static methods overall. Let me try to isolate the issue in these tests.

**Comment by ppshobi** [comment]
It was really my issue, where I was running the docker container with wrong master-key 👎
