### ISSUE TITLE
Still support PHP 7.2?

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-php#136]
Hello the PHP community 👋 

Since [PHP 7.2 has reached is EOL](https://www.php.net/supported-versions.php), should we keep supporting this version in this package?
Concretely it means removing the CI tests with PHP 7.2.

On the other hand, I can guess this is still used a lot in production.

What do you think about it? 🙂

Thanks again to everyone for your involvement in this project!

**Comment by Guikingone** [comment]
I'm okay for keeping it as it still widely used in projects.

**Comment by ppshobi** [comment]
Even PHP 7.4 is going to be EOL by end of this year. But as a library we should support more version's, I guess. companies don't like to do major upgrades very fast. So, unless we have a specific reason to drop support for 7.2 let's keep it that way

Also, if we are dropping support for 7.2 in future versions people can use the existing versions without any issue.

**Comment by curquiza** [comment]
Good to have your opinion on it then! I close this issue since it does not seem useful for the moment. 
Feel free to let us know if you want to reopen it 😊
