### ISSUE TITLE
Bump minimum version required upto PHP 7.2

### ISSUE THREAD

**Issue by ppshobi** [meilisearch/meilisearch-php#15]
https://www.php.net/supported-versions.php

Already PHP 7.2 is in security support mode only. Especially considering the fact that this library is we could support the latest version of PHP. And we could use/enforce the latest language features.

**Comment by curquiza** [comment]
Hi! I've just seen you've made a PR about testing multiple PHP versions (#14).
Don't you think we should only test PHP 7.2 7.3 and 7.4 according to your remark? 🙂

**Comment by ppshobi** [comment]
Yes, I think it should be that way. But while writing this issue, the minimum version according to composer.json in 7.0. So, once the decision is made from your end, we could update the build matrix.

**Comment by curquiza** [comment]
I agree with your point of view: we should only require 7.2 and more. Then could you update your PR accordingly to avoid another PR? 🙂

**Comment by ppshobi** [comment]
PR updated, Please check,
