### ISSUE TITLE
Could not delete document

### ISSUE THREAD

**Issue by payssion-liao** [meilisearch/meilisearch-php#158]
It seems i can't delete document with this lib.
Step1:
```
write_log($post_id); // $post_id=281
$rs = $client->index('docindex')->deleteDocument($post_id);
write_log($rs);
```
$post_id is right and i can get the right return from deleteDocument which is 
```
(
    [updateId] => 262
)
```
And i can also confirm that this action is processed by visiting http://localhost:7700/indexes/docindex/updates/262.

Step2:
Access http://127.0.0.1:7700/indexes/docindex/documents, i can still see the document with id:281 was there.

Step3:
I use curl -X DELETE 'http://localhost:7700/indexes/docindex/documents/281 to delete the document. And it is done perfectly.

I don't know why, please let me know if i'm in the wrong position. Thanks.

**Comment by alallema** [comment]
Hello @payssion-liao!
Thanks a lot to raise this issue but I need some details about the context:
- Which version of Meilisearch did you use?
- Which version of meilisearch-php did you use?
- Can you give the JSON response of http://localhost:7700/indexes/docindex/updates/update_id after running the code.
- And this one also http://localhost:7700/indexes/docindex/documents/document_id before and after running the code if it's different.

**Comment by payssion-liao** [comment]
Hi @alallema, Thanks for the quick reply and here are the details.
1. Meilisearch version: 0.20.0
2. Meilisearch-php version: 0.17.1
3. Response:
```
{"status":"processed","updateId":321,"type":{"name":"DocumentsDeletion","number":1},"duration":0.002365708,"enqueuedAt":"2021-04-22T02:18:08.769868Z","processedAt":"2021-04-22T02:18:08.772907Z"}
```
4. {"id":377,"title":"111222","content":"333333","url":"https://doc.local.com/?p=377", "status": "open"}
    The only difference before and after the deletion is the field `status`. Status is altered from 'open' to 'closed'. Is this the reason why i can't delete it? I thought it should be deleted by id. Waiting for your reply :)

**Comment by alallema** [comment]
Hi @payssion-liao, Thanks for the quick reply too.

> Status is altered from 'open' to 'closed'. 

MeiliSearch would never modify or update a document by itself. Maybe your code adds or updates a document after your deletion.
- You should verify on this route:
`http://localhost:7700/indexes/docindex/updates/`
If any `DocumentsAddition` or `DocumentsUpdate` appears between the moment you delete the document and the moment you require it.
- Check log Meilisearch in terminal to see what happens after your deletion.

I hope this will help you.

**Comment by ppshobi** [comment]
@payssion-liao were you able to figure out this issue?

**Comment by payssion-liao** [comment]
@ppshobi yeah, we talked about that on email. Even though i would still like to share the statements here.
It seems that you need to keep the document the same as original so that you can delete it later.
