### ISSUE TITLE
Dropping support for php 7.2

### ISSUE THREAD

**Issue by codedge** [meilisearch/meilisearch-php#165]
Would it be alright to drop support for php 7.2 as it is unmainted, not even receiving security updates anymore?
Php 7.3 isn't mainted anymore as well, but at least gets security updates. So that is kind of understandable to still support it.

Lmk if you would accept a PR on this.

**Comment by curquiza** [comment]
Hello @codedge 😄 

We already had a discussion about it in January, but maybe the opinions changed: https://github.com/meilisearch/meilisearch-php/issues/136

**Comment by Guikingone** [comment]
Hi 👋🏻 

As described here: https://www.php.net/supported-versions.php

Supporting 7.2 is not "supported" anymore as PHP itself does not merge new things in it, the main concern is 7.3 for me, as this library is not "stable" (for now, there's no `v1`), supporting 7.3 to 8.0 can be enough, when 8.1 is available, adding support for it can be a good idea, this way, the support for 7.3 can be dropped. 

That's just my opinion 🙂

**Comment by codedge** [comment]
When waiting for 8.1 then even 7.3 is EOL. So you always support one EOL version of php for this package.

> this library is not "stable" (for now, there's no v1)

Understandable point, but dropping a php version is not a major change. A minor version bump seems to be totally ok. So as an example `0.18` could drop php 7.2. Those who still run `7.2` can use it, and all other get the newer releases.

Here are [some stats](https://blog.packagist.com/php-versions-stats-2020-2-edition/) from packagist.com about versions used which feeld like 7.3/7.4 cover over 60% of all. 

If you argue to support 7.2 because it is ["still widely used"](https://github.com/meilisearch/meilisearch-php/issues/136#issuecomment-764747020) (taken from #136) you could do same for 5.6... and if this starts, I am off 😄 

As you said, just my opinion. @curquiza It's your turn now 😉

**Comment by Guikingone** [comment]
> When waiting for 8.1 then even 7.3 is EOL. So you always support one EOL version of php for this package.

Supporting 7.3 to 8.0 can be enough IMHO.

> Understandable point, but dropping a php version is not a major change.

Agree, that's why your proposal of dropping the support for 7.2 in 0.18 is a good idea IMHO.

I'm not for continuing to support 7.2 if that's the question 😄

**Comment by curquiza** [comment]
Hello @Guikingone, nice to see you again 😁

Thanks @codedge for sharing these stats from packagist! 🙂

I'm ok to maintain 7.3 to 8.0 :)

> Understandable point, but dropping a php version is not a major change. A minor version bump seems to be totally ok. So as an example 0.18 could drop php 7.2. Those who still run 7.2 can use it, and all other get the newer releases.

Since we are not stable we use the semantic versioning as `0.X.Y` where `X` is our "major". It means, for each breaking change we increase the `X`, otherwise only the `Y`. Following your point ("dropping a php version is not a major change") we are going to release a `v0.17.3` when dropping the 7.2 support.
Does this make sense to both of you, or would you rather a `v0.18.0` instead of a `v0.17.3`?

**Comment by Guikingone** [comment]
IMHO, releasing the PHP "upgrade" in a patch version isn't a valid behaviour according to semver: 

> PATCH version when you make backwards compatible bug fixes.

Changing the PHP minimal version is not a bug fix, (even if does not introduce BC breaks) I tend to agree with @codedge to release it via `0.18`

PS: Nice to be back @curquiza, pretty tough period at work 😄

**Comment by codedge** [comment]
Strictly speaking, a patch version bump like `0.17.0 -> `0.17.1` is enough when updating an underlying package or language dependency. However, it does mean users will be stuck on the older version. If an important bugfix comes along, those users will be stuck on an unpatched version.

For that reason, I prefer minor version bumps like `0.17.0` -> `0.18.0` instead. Increasing the minor version instead of the patch version doesn’t do any harm, and if a critical patch comes along you can still backport it.

So, we are all right :D .. it is probably a thing of personal preference.

I would prepare a PR for the change and @curquiza you can decide meanwhile.

**Comment by curquiza** [comment]
I also would rather increase the minor (release a v0.18.0) for this kind of change 🙂 Thanks for your return!
