### ISSUE TITLE
Http requests use json_encode which can fail and cause a TypeError.

### ISSUE THREAD

**Issue by tao** [meilisearch/meilisearch-php#180]
**Description**
If you send content to be updated or inserted with the Client, it uses `json_encode` before sending the request. If the content is not UTF-8 encoded... in my case I believe it was from using a non-english language, then parsing the content to json can fail. Take a look at the post method for example:

```php
    public function post($path, $body = null, $query = [])
    {
        $request = $this->requestFactory->createRequest(
            'POST',
            $this->baseUrl.$path.$this->buildQueryString($query)
        )->withBody($this->streamFactory->createStream(json_encode($body)));

        return $this->execute($request);
    }
```

The POST, PUT, and PATCH methods all use `createStream()` with `json_encode`.

When `json_encode` fails it just returns `false`... but the interface method `createStream(string $content = '')` requires content to be a string, so when it encounters a boolean from the failed json encoding it crashes with a `TypeError`.

The functions need to catch the error and maybe use a custom error message with a warning, or use a private function to check for encoding errors before uploading: 

```php
        try {
            $stream = $this->streamFactory->createStream(json_encode($body));
        } catch (\TypeError $e) {
            throw new \TypeError('Failed to parse content... make sure it's UTF-8 encoded.');
        }
```

If it fails you can also call `json_last_error()` and you'll get an INT which explains reason [why the json parser failed](https://www.php.net/manual/en/function.json-last-error.php#119958). In my code I got a `5: JSON_ERROR_UTF8` but as you can see there are a few reasons why the parser can fail.

**Current behavior**
This is the current error I receive:

```php
  Nyholm\Psr7\Factory\Psr17Factory::createStream(): Argument #1 ($content) must be of type string, bool given, called in /Users/daniel/Code/www.llresearch/vendor/meilisearch/meilisearch-php/src/Http/Client.php on line 111

  at vendor/nyholm/psr7/src/Factory/Psr17Factory.php:33
     29▕
     30▕         return new Response($code, [], null, '1.1', $reasonPhrase);
     31▕     }
     32▕
  ➜  33▕     public function createStream(string $content = ''): StreamInterface
     34▕     {
     35▕         return Stream::create($content);
     36▕     }
     37▕
```
     
**Temporary solution**
I was able to discover and overcome the error by forcing UTF-8 encoding, however it took a whole afternoon to debug so a warning would be useful. One reason why it took a long time to debug is that it threw a `TypeError` instead of an `Exception`.

```php
    // $document["content"] = $content;
    $document["content"] = utf8_encode($content);
```

**Comment by alallema** [comment]
Hi @tao!
Thanks a lot to raise this error and coming with a solution. If you want to create a PR to fix it would be with pleasure. If not no problem I will do it.
Sorry about this!

**Comment by tao** [comment]
I haven't created a pull request because I'm not sure how you prefer to handle errors... and if you want to throw a custom error and add a note to the docs.

**Comment by tao** [comment]
Maybe something like this:

```php
  public function patch($path, $body = null, $query = [])
    {
        $data = $this->prepareRequest($body);

        $request = $this->requestFactory->createRequest(
            'PATCH',
            $this->baseUrl.$path.$this->buildQueryString($query)
        )->withBody($this->streamFactory->createStream($data));

        return $this->execute($request);
    }

    private function prepareRequest($body)
    {
        $request = json_encode($body);

        if (!$request) throw new \Exception(json_last_error_msg());

        return $request;
    }
```

And the response will be something like this:

```bash
   Exception

  Malformed UTF-8 characters, possibly incorrectly encoded

  at vendor/meilisearch/meilisearch-php/src/Http/Client.php:153
    149▕     private function prepareRequest($body)
    150▕     {
    151▕         $request = json_encode($body);
    152▕
  ➜ 153▕         if (!$request) throw new \Exception(json_last_error_msg());
    154▕
    155▕         return $request;
    156▕     }
    157▕
```

**Comment by codedge** [comment]
The user should make sure that the content send to MS has a proper encoding. If the json encoding fails the code should definitely throw an exception, good point.

I would support throwing an, f. ex. `FailedJsonEncodingException`, exception with a proper message (with the `json_last_error_message`.

**Comment by alallema** [comment]
@tao,
I forgot can you provide a document to try to reproduce the error?
Thanks again

**Comment by tao** [comment]
It's not working with some Bulgarian, German, Spanish, French markdown files... and some English ones.

Bulgarian: [1972-03-01.0300.md](https://github.com/meilisearch/meilisearch-php/files/6671470/1972-03-01.0300.md)
German: [2015-12-05.1205.md](https://github.com/meilisearch/meilisearch-php/files/6671474/2015-12-05.1205.md)
French: [1986-12-14.1214.md](https://github.com/meilisearch/meilisearch-php/files/6671765/1986-12-14.1214.md)

I think the english files using this a strange comma:  `’` instead of `'` or maybe this one ` “` instead of `"` ? I'm not sure why they use different commas but we have lots of translators so they probably have strange keyboards.

I am having trouble determining an exact which character is breaking the `json_encode` function... but I also found you can parse a flag to overcome this error:

```
json_encode($body, JSON_INVALID_UTF8_SUBSTITUTE)
```

The flag `JSON_UNESCAPED_UNICODE` didn't seem to fix the error but `JSON_INVALID_UTF8_SUBSTITUTE` was OK.

It seems like you can test it with this:

```php
$test = utf8_decode("Düsseldorf")
json_encode($test)

=> false
```

**Comment by alallema** [comment]
Hi @tao,
For the PR, I suggest like @codedge that you create a custom `Exception` like `FailedJsonEncodingException` with the specific message of `json_last_error_message`. You can take an example from `InvalidArgumentException`.
Your codes for fixing the bug seem to be good.
But again, we love to work with the community, so if you want to create a PR, it would be great! But if you don't want it or didn't have time, it's okay. Don't hesitate to ask if you have questions and check our [contributing guidelines](https://github.com/meilisearch/meilisearch-php/blob/main/CONTRIBUTING.md).
Thanks a lot

**Comment by alallema** [comment]
Hi @tao!
I try to reproduce your issue but I can't get it. If I put your file in the document["content"] it works:
``` PHP
$contents[0] = file_get_contents('1972-03-01.0300.md');
$contents[1] = file_get_contents('1986-12-14.1214.md');
$contents[2] = file_get_contents('2015-12-05.1205.md');
$documents = [
    ['id' => 123,  'lang' => 'Bulgarian'],
    ['id' => 456,  'lang' => 'French',],
    ['id' => 1,    'lang' => 'German'],
];
for ($index = 0; $index <= 2; $index++) {
    $documents[$index]["content"] = $contents[$index];
}
$client->index('mdFile')->addDocuments($documents);
```
<img width="531" alt="Screenshot 2021-06-22 at 11 45 10" src="https://user-images.githubusercontent.com/16155041/122903540-c7a09880-d34f-11eb-9d1d-7e35974969a5.png">

And if I transformed your `md` file into `json` file it's work too.
<img width="531" alt="Screenshot 2021-06-22 at 11 48 00" src="https://user-images.githubusercontent.com/16155041/122903600-d8e9a500-d34f-11eb-9ba8-5282d9525cbe.png">

I think I'm missing something. Can you explain to me how to reproduce your problem?
Thank you

**Comment by codedge** [comment]
@alallema 

Although not fully clarified here what went wrong, I added the check for the `json_encode` and throw an exception. I think that makes it more clear for the user for similar errors in the future.

**Comment by tao** [comment]
@alallema @codedge Although the issue is closed now (thanks!) I've been working on finding out why this occurs in my code but you're not able to replicate it. I have an update which might be useful to know.

Since MeiliSearch has a 1000 word limit, I was splitting my long articles into chunks and uploading all these chunks to the index. When you use `str_split` is splits the string at a byte level not a char level... so it may cause problems with UTF-8 encoding as it's not a unicode-aware function.
