### ISSUE TITLE
Traits break contract for not reducing any complexity

### ISSUE THREAD

**Issue by codedge** [meilisearch/meilisearch-php#182]
The ways traits are used in this lib feel a bit strange. Take the 

* `HandlesDocuments` trait or
* `HandlesDumps` trait
* ... and many more...

Both are only used _once_. Further traits access properies 

* `HandlesDocuments` accesses `http`
* `HandlesDumps` accesses `dumps`

that are not declared inside the trait but in the class they are used in. Even with the `@property` notation added inside the traits, it is not clear to which property you are refering. Using the `@property` notation is meant for magic methods. 

Why using a trait for methods that are only used in _one_ place? Directly implementing would have the same effect and would provide a cleaner style.

I was coming across that when I wanted to increase PHPstans level to `2`. With the current implementation this seems not possible.

Let me know if the methods implemented in traits can be moved to the classes itself and/or how PHPstan can correctly determine the traits properties _that are not defined inside the trait itself_.

<img width="1275" alt="grafik" src="https://user-images.githubusercontent.com/4409904/123870779-20b19300-d933-11eb-9958-631a4f51b0b0.png">

**Comment by alallema** [comment]
Hi @codedge,
Thank you for this report. There was a [refactor](https://github.com/meilisearch/meilisearch-php/pull/43) of this SDK by a great contributor @ppshobi to fit with SOLID compliance.
I think it could answer this one far better than me.

**Comment by ppshobi** [comment]
feel free to open PR to fix it 👍
