### ISSUE TITLE
Can't set updateAttributesForFaceting

### ISSUE THREAD

**Issue by stevebeyatte** [meilisearch/meilisearch-php#184]
**Description**
I’m running into issues configuring facets on my indices. [The docs](https://docs.meilisearch.com/reference/features/settings.html#attributes-for-faceting) say I can set my filter attributes with updateAttributesForFaceting() but it doesn't appear to be working

**Expected behavior**
I expect to be able to set filterable attributes via updateAttributesForFaceting()

**Current behavior**
What happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/1461804/124123259-54281680-da34-11eb-965b-e3f3501d4252.png)
![image](https://user-images.githubusercontent.com/1461804/124123301-6609b980-da34-11eb-8a92-798743ea9ebc.png)

**Environment:**
- OS: Mac 10.15.7
- MeiliSearch version: v0.21.0rc0--7700
- meilisearch-php version: 0.18.3

**Comment by curquiza** [comment]
Hello @stevebeyatte 
[As you can see in the README](https://github.com/meilisearch/meilisearch-php#-compatibility-with-meilisearch) this package is only compliant with v0.20 of MeiliSearch. It will be updated soon 😁
Thanks for testing the RC of MeiliSearch!

**Comment by stevebeyatte** [comment]
Ah, Takeout defaulted to the latest RC, that makes sense. Thanks!

**Comment by curquiza** [comment]
Closing then 🙂
