### ISSUE TITLE
Got the issue with  Invalid URL: scheme is missing

### ISSUE THREAD

**Issue by dungnh** [meilisearch/meilisearch-php#202]
I have installed the newest MeiliSearch with MAC, Valet and Laravel 8 with Scout. And I got exception when run meilisearch function: 

```
Symfony\Component\HttpClient\Psr18RequestException

Invalid URL: scheme is missing in "1234567890/indexes/xxxxxx/documents". Did you forget to add "http(s)://"?
```

Please help how can I resolve this issue? 
I guest it can be issue with http on localhost, but have no idea to make it works. I can work with http on local with meilisearch v0.20.

**Environment:**
- OS: MAC Big Sur
- PHP  v8.3
- MeiliSearch version: v.0.21.1
- meilisearch-php version: v0.19.1
- Laravel ^8.14
- Laravel Scout ^9.2

**Comment by curquiza** [comment]
Hello @dungnh!

What is your MeiliSearch config (`MEILISEARCH_HOST`)?
Can you ping your localhost MeiliSearch? Try:
```bash
curl http://127.0.0.1:7700/version
```

**Comment by dungnh** [comment]
Hi @curquiza,

Thank for replying. Don't mine, I have made it works.
My bad when there are duplicate the meilisearch host configuration.

BTW, my config is: 

`MEILISEARCH_HOST=http://127.0.0.1:7700
`

And I have run to check my the Meilisearch version: 

```
curl http://127.0.0.1:7700/version
{"commitSha":"unknown","commitDate":"unknown","pkgVersion":"0.21.1"}%
```

**Comment by curquiza** [comment]
glad to read you made it work! :)

I close this issue then!
