### ISSUE TITLE
Unable to `updateSettings` for an index

### ISSUE THREAD

**Issue by aocneanu** [meilisearch/meilisearch-php#204]
**Description**
I want to update and index settings using the script below

```php
...
$settings = $index->getSettings();
$index->updateSettings($settings);
```

**Expected behavior**
The settings would be successfully updated

**Current behavior**
An exception is thrown

```php
MeiliSearch\Exceptions\ApiException with message 'Json deserialize error: invalid type: sequence, expected a map at line 1 column 190'
```

If I use `updateSearchableAttributes` or `updateFilterableAttributes` it works as expected

**Environment (please complete the following information):**
- OS: [e.g. Mac OSX]
- MeiliSearch version: [e.g. v.0.21.1]
- meilisearch-php version: [e.g v0.19.0]

**Comment by alallema** [comment]
Thanks, @aocneanu  for raising this issue.
And you get a good point. The API only accept:
```
"synonyms": {},
```
or
```
"synonyms": null,
```
And when you run this code it sends this:
```
"synonyms": [],
```
I'm going to look deeper into where the problem comes from.
Thanks again
