### ISSUE TITLE
🙏 Add support for MeiliSearch v0.22.0

### ISSUE THREAD

**Issue by wassim** [meilisearch/meilisearch-php#206]
[v0.22.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.22.0) introduces support for sorting at query time, which is a critical functionality for a lot of users.

**Comment by curquiza** [comment]
Hello @wassim
We have just released v0.22.0 (1h ago) so it can take more time
However
- The docs related to the sort have just been released: https://docs.meilisearch.com/reference/features/sorting.html
- A blog post has been released: https://blog.meilisearch.com/whats-new-in-v0-22/
- The meilisearch-php branch for the compatibility with v0.22.0 is not merged yet, but will be during at the beginning of this week -> https://github.com/meilisearch/meilisearch-php/pull/200

**Comment by curquiza** [comment]
MeiliSearch Php [v0.19.1](https://github.com/meilisearch/meilisearch-php/releases/tag/v0.19.1) is released, we can close this issue
