### ISSUE TITLE
Implementation of a Json Serializer

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-php#209]
**Description**
As a result of this [issue](https://github.com/meilisearch/meilisearch-php/issues/204), it appears that `json_decode` transforms
```json
"synonyms": {}
```
into
```php
["synonyms"]=>
  array(0) {
}
```
In the same way as:
```json
"stopWords": []
```
become:
```php
["stopWords"]=>
  array(0) {
}
```
The problem appears when you send back the synonyms array to the MeiliSearch API who only take:
```json
"synonyms": {},
```
or
```json
"synonyms": null,
```
It could be useful to implement our own specific JsonSerializer to check if every data send back to MeiliSearch API are well-formatted.

In the meanwhile a patch will be created [see](https://github.com/meilisearch/meilisearch-php/pull/208).

**Comment by norkunas** [comment]
We could use `JSON_FORCE_OBJECT` flag to encode the json so empty arrays would be objects always
