### ISSUE TITLE
updateFilterableAttributes

### ISSUE THREAD

**Issue by tao** [meilisearch/meilisearch-php#210]
I'm trying to call `updateFilterableAttributes` in my code... and it seems to exist in this repository in the tests but I'm unable to figure it out?

The docs say you can do this but I can't call that method myself.
```
$client->index('movies')->updateFilterableAttributes([
  'genres',
  'director'
]);
```

**Comment by curquiza** [comment]
Hello! 

What is your MeiliSearch version? And what is the error?
```
curl http://127.0.0.1:7700/version
```

**Comment by tao** [comment]
Hey @curquiza, I'm using a brand new MeiliSearch server, with v0.21.0 and the PHP library is also up to date.

The method is just available to use:

```php
Call to undefined method MeiliSearch\Endpoints\Indexes::updateFilterableAttributes()
```

I was able to get it working this way:

```php
$index = $this->client->createIndex($this->name, ['primaryKey' => 'id']);
$index->updateSettings([
    'filterableAttributes' => ['type', 'locale'],
]);
```

But wondering why the docs mention this method but we can't access it... although it exists in the tests.

**Comment by alallema** [comment]
Hi @tao,
Indeed the method exists in the tests and when I try it on my side it works.
This method is only available from meilisearch-php: v0.19.1.
However, all the sub-settings methods are not declared as the current `setSettings`, `getSettings, and `updateSettings`.
Is this the only sub-settings method that won't work? Can you try an another one like `updateSynonyms`?
Thanks

**Comment by tao** [comment]
Okay, I see there was a mistake with a version mismatch on my side... sorry about that -- you can close this issue. 

I find it difficult to keep track of the changes and I know MeiliSearch is changing a lot but could I suggest making a Change Log so it's easier to track what changes between releases?

**Comment by alallema** [comment]
Hi @tao!
Sorry for the inconvenience. You can find the ChangeLog [here](https://github.com/meilisearch/meilisearch-php/releases) for the PHP SDK and [here](https://github.com/meilisearch/MeiliSearch/releases) for MeiliSearch.
Here is an article on the last release [here](https://blog.meilisearch.com/whats-new-in-v0-22/).
Normally, in the future, we will also announce the release of SDKs in the Slack community [here](meilicommunity.slack.com).
Don't hesitate if you have any suggestions 😊

**Comment by alallema** [comment]
I close this issue don't hesitate to re open it if you need it!
