### ISSUE TITLE
The default HTTP client can't handle non-JSON response bodies

### ISSUE THREAD

**Issue by MoritzLost** [meilisearch/meilisearch-php#211]
**Description**

I just went through a bit of painful debugging because I couldn't figure out why my indexing POST requests were failing in production. This is the error message I got:

> MeiliSearch\Exceptions\FailedJsonDecodingException
> Decoding json payload failed: "Syntax error".
> Caused by: JsonException 

The error came from `MeiliSearch\Http\Client::parseResponse()` which uses `MeiliSearch\Http\Client::jsonDecode()`.

Now the actual problem was that in production, the MeiliSearch instance is sitting behind an nginx reverse proxy and the POST request was hitting the `max_client_body_size`, so nginx returned a 413 error with the default HTML error page.

This was difficult to debug since it only happened in production (I use the docker image for testing, so no reverse proxy in the test environment).

**Expected behavior**

The `Client::parseResponse` method should be able to handle non-JSON responses more gracefully so that a failing request in production produces a helpful error message. The client could either check the `Content-Type` header of the response and only parse it as JSON if appropriate. Or catch the exception thrown by `jsonDecode` and throw a more helpful exception with the HTTP response code.

**Current behavior**

If the MeiliSearch server returns a non-JSON response, you get a `FailedJsonDecodingException` with no indication regarding the actual response code and content.

**Environment**

- OS: Ubuntu 20.04
- MeiliSearch version: v.0.22.0
- meilisearch-php version: v0.19.1

**Comment by alallema** [comment]
Hi @MoritzLost,
Thanks for raising this issue. Indeed the `Client::parseResponse` method should be able to return a useful hint and a real error message.
