### ISSUE TITLE
Associative array of filters does not work as documented

### ISSUE THREAD

**Issue by macbookandrew** [meilisearch/meilisearch-php#212]
**Description**
Using [faceted search](https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#example-3) does not work quite as expected.

**Expected behavior**
I expected to be able to pass an associative array of filters for faceted search as written in [the documentation](https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#example-3).

Expected:

```php
$results = $index->search('', ['filter' => [['refinement-color' => 'Willow', 'refinement-color' => 'White']]]);
// $results should be an instance of MeiliSearch\Search\SearchResult
```

**Current behavior**
Here’s the call and response:

```php
$results = $index->search('', ['filter' => [['refinement-color' => 'Willow', 'refinement-color' => 'White']]]);

MeiliSearch\Exceptions\ApiException with message 'Invalid facet expression, expected String, [String], found: {"refinement-color":"White"}'
```

The only way I got it to work was by converting the associative array to an array of `key=value` pairs:

```php
$results = $index->search('', ['filter' => [['refinement-color=Willow', 'refinement-color=White']]])
// $results is an instance of MeiliSearch\Search\SearchResult
```

**Environment (please complete the following information):**
- OS: macOS
- MeiliSearch version: v0.22.0
- meilisearch-php version: v0.19.1

**Comment by macbookandrew** [comment]
Questions:

1. Is the [documentation](https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#example-3) incorrect? (should it instead be a numerically-indexed array of `key=value` strings?)
2. Should the PHP client’s [`jsonEncode` method](https://github.com/meilisearch/meilisearch-php/blob/e8151e124f046b87e96df3bf1480b7f8aae2060e/src/Http/Client.php#L211) convert associative arrays to indexed arrays of `key=value` strings?
3. Should the Meilisearch server handle the JSON object produced by json-encoding an associative array, rather than requiring an array of `key=value` strings?

**Comment by macbookandrew** [comment]
Here’s how I ended up working around this issue: https://gist.github.com/macbookandrew/8baf9144cc8c359728410347e6f92e95

**Comment by alallema** [comment]
Hi @macbookandrew,
Thanks for raising this issue. You totally right there is a mistake on the documentation it's on me. ​It should be:
``` php
$client->index('movies')->search('thriller', ['filter' => [['genres = Horror', 'genres = Mystery'], 'director = "Jordan Peele"']]);
```
For your trouble this way should work:
``` php
$results = $index->search('', ['filter' => ['refinement-color = Willow', 'refinement-color = White']]);
```
It could also work with this syntaxe:
``` php
$results = $index->search('', ['filter' => ['refinement-color = Blue', ['refinement-color = Willow', 'refinement-color = White']]]);
```
Or this one:
``` php
$results = $index->search('', ['filter' => [['refinement-color = Willow', 'refinement-color = White']]]);
```
I'm sorry for the inconvenience. I hope it's going to resolve your problem.

**Comment by macbookandrew** [comment]
Thanks!

**Comment by macbookandrew** [comment]
@alallema would you be interested in a PR with [this fix](https://gist.github.com/macbookandrew/8baf9144cc8c359728410347e6f92e95) so associative arrays or objects work as a developer might intuitively expect? Or would you prefer to require them to match the Meilisearch server format (array of `"key=value"` strings)

**Comment by alallema** [comment]
Hi @macbookandrew,
For now, I think it's better to keep the server format, it allows us to keep consistency between the different SDKs.
Thanks for asking
