### ISSUE TITLE
Invalid JSON: unknown field `filter`

### ISSUE THREAD

**Issue by jrmypttrsn** [meilisearch/meilisearch-php#216]
**Description**
Exception when trying to apply filter to search query with Laravel Livewire

**Expected behavior**
Filter search query based on selected filter

**Current behavior**
500 error in production

MeiliSearch\Exceptions\ApiException in development
Invalid JSON: unknown field `filter`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `filters`, `matches`, `facetFilters`, `facetsDistribution` at line 1 column 35

**Screenshots or Logs**
Link on [Flare](https://flareapp.io/share/NPL34dzm#F79)
Invalid JSON: unknown field `filter`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `filters`, `matches`, `facetFilters`, `facetsDistribution` at line 1 column 35
![Screen Shot 2021-09-30 at 14 51 39](https://user-images.githubusercontent.com/16291625/135521314-94b11fa6-9afb-461d-9c6c-786cba8a623a.png)

**Environment (please complete the following information):**
- OS: [OS X]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.83 

- MeiliSearch version: [e.g. v.0.20.0]
- meilisearch-php version: [e.g v0.19.1]

**Comment by eliasjtg** [comment]
You must synchronize your meilisearch version with the meilisearch-php

This happening because one expects filters and other use filter

If you're sure that is'nt your problem, review your code, in some place you are setting index option manually

**Comment by jrmypttrsn** [comment]
Both versions up to date, I mistakenly didn't include the correct version in my bug report. I'm using 0.22.0 for MeiliSearch.

None of my code has changed, this just started happening on a recent composer update.

**Comment by curquiza** [comment]
Hello @jrmypttrsn!

Are you sure you are using MeiliSearch v0.22.0?
This is typically an error you get when using an old MeiliSearch version that does not use the `filter` parameter.
Please check with
```bash
curl -s http://127.0.0.1:7700/version
```

You might want to replace `http://127.0.0.1:7700` by the server address of your MeiliSearch instance.

**Comment by jrmypttrsn** [comment]
@curquiza Everything is up to date. It looks like it's something with Laravel Scout. Too many breaking changes with Meilisearch to use in production so I'm going to implement something else for search. Thanks anyway.

**Comment by curquiza** [comment]
Sorry for the disappointment! Feel free to require our help if you change your mind. The whole team is available to help you through the breaking changes.
Also you can consult:
- the release changelogs: https://github.com/meilisearch/MeiliSearch/releases
- the blog post about the new release, cf the [v0.22.0 article](https://blog.meilisearch.com/whats-new-in-v0-22/)

**Comment by blackrabbit944** [comment]
@jrmypttrsn @curquiza i had the same problems also.

this is my salution:

···
       // meilisearch-php 0.19.0 is compatible with meilisearch server 0.21.0...
        // if (version_compare(MeiliSearch::VERSION, '0.19.0') >= 0 && isset($searchParams['filters'])) {
        //     $searchParams['filter'] = $searchParams['filters'];

        //     unset($searchParams['filters']);
        // }
···

You need to comment this part of the code at:

/vendor/laravel/scout/src/Engines/MeiliSearchEngine.php , Line 130
