### ISSUE TITLE
Simple Documentation Typo

### ISSUE THREAD

**Issue by almasaeed2010** [meilisearch/meilisearch-php#250]
In the readme there is a typo in the php syntax:

It's using the wrong array syntax:
```php
$index->search(
  'wonder',
  {
    filter: ['id > 1 AND genres = Action']
  }
);
```

It should be:
```php
$index->search(
  'wonder',
  [
    'filter' => ['id > 1 AND genres = Action']
  ]
);
```

I've created a PR to fix the typo.

Thanks!

**Comment by curquiza** [comment]
thank you for this issue @almasaeed2010 and for the PR! :)
