### ISSUE TITLE
Test the `code` of the `ApiException` exception instead of the `message`

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-php#252]
In tests, when an `ApiException` exception is tested, often the message of the exception is also checked.

```php
$this->expectException(ApiException::class);
$this->expectExceptionMessage('internal error');
```

This is something we don't want to do. We only want to check the `code` of the error in the tests, not the `message` itself that can often break on the MeiliSearch side.

FYI, MeilISearch returns 4 fields when raising an error: `message`, `code`, `type`, and `link`. Only the `code` should be tested.

⚠️ Should be done once MeiliSearch v0.24.0 is released

**Comment by norkunas** [comment]
But if message would be still in tests, then people could easily find what messages are expected in code without navigating externally :)

**Comment by curquiza** [comment]
I'm not sure to get your point? Can you give an example?

**Comment by norkunas** [comment]
For example: I want to know what exceptions this library could throw and and what are the messages without going to documentation because probably I wouldn't find them there :D

**Comment by curquiza** [comment]
Got it :)

However, this is not the job of this package to be the MeiliSearch documentation instead of our [current documentation](https://docs.meilisearch.com/). You can find all the `code` errors and the description of them on [this page](https://docs.meilisearch.com/errors/#meilisearch-errors).

If
- the descriptions are not explicit enough on this page
- this page is not easy to find in the docs
This is an issue on the documentation side and I will transfer the problem to them.

But this should not be additional work for the maintainer of this package. I hope you understand :)

**Comment by norkunas** [comment]
ok, no problem :)

**Comment by TeddyBear06** [comment]
Hello @curquiza,

First of all, thanks to meilisearch team/community, I use it and love it, wonderfull.

I would like to work on this one.

I already started to install the development env following [Development Workflow](https://github.com/meilisearch/meilisearch-php/blob/main/CONTRIBUTING.md#development-workflow) but I got some installing/testing artifacts.

1. During ```composer install```, I was asked to allow plugins installation from [phpstan](https://github.com/phpstan/extension-installer):

```
Do you trust "phpstan/extension-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?]
``` 
 
Resulting in the following line added to the composer.json if I answer _y_: 
```json
"config": {
  "allow-plugins": {
    "phpstan/extension-installer": true
  }
}
```

Maybe we need to specify to answer _no_ during ```composer install``` or add it the the composer.json (or something else 😊).

2. The meilisearch installation command ```curl -L https://install.meilisearch.com | sh``` from this [code block](https://github.com/meilisearch/meilisearch-php/blob/main/CONTRIBUTING.md#tests-and-linter) created a _meilisearch.exe_/_meilisearch_ executable at the root of the project.

Maybe the root project is not the right place to execute the Meilisearch install command but it can be specified in the _Development Workflow_ as the previous command is a ```composer install``` wich need - obviously - to be executed at the root project directory or, we can exclude executables (and data folders) to be tracked into the project .gitignore (or something else 😊).

**Comment by alallema** [comment]
Hi @TeddyBear06,
Thank you for raising this issue! You are right, this step should be added in the CONTRIBUTION guide depending on the version of `composer` the user has. And I wonder if the `d` option would not solve our problems I think it's for `downloading` so maybe it will download the package without adding lines to the `composer.json. file?
In any case, feel free to add this in the `CONTRIBUTING` it will be so nice!
