### ISSUE TITLE
getOrCreateIndex broken?

### ISSUE THREAD

**Issue by francoism90** [meilisearch/meilisearch-php#260]
**Description**
It throws an exception, instead of creating an index, if it doesn't exist.

Think something is wrong here:

```
 if (\is_array($e->httpBody) && 'index_not_found' === $e->errorCode) {
..
}
```

**Expected behavior**
Should create index when index doesn't exist.

**Current behavior**
```
MeiliSearch\Exceptions\ApiException 

  Index books_index not found

  at vendor/meilisearch/meilisearch-php/src/Http/Client.php:211
    207▕ 
    208▕         if ($response->getStatusCode() >= 300) {
    209▕             $body = $this->jsonDecode($response->getBody()->getContents()) ?? $response->getReasonPhrase();
    210▕ 
  ➜ 211▕             throw new ApiException($response, $body);
    212▕         }
    213▕ 
    214▕         return $this->jsonDecode($response->getBody()->getContents());
    215▕     }

      +6 vendor frames 
  7   app/Actions/Search/CreateIndexes.php:15
      MeiliSearch\Client::getOrCreateIndex()

      +1 vendor frames 
  9   app/Actions/Search/CreateIndexes.php:24
      Illuminate\Support\Collection::each()
```

**Screenshots or Logs**
See above.

**Environment (please complete the following information):**
- OS: Linux
- MeiliSearch version: `meilisearch 0.23.1-1`
- meilisearch-php version: `"meilisearch/meilisearch-php": "^0.20.0",`

**Comment by alallema** [comment]
Hi @francoism90,
Thanks for raising this issue. If you check the [releases](https://github.com/meilisearch/meilisearch-php/releases/tag/v0.20.0) you can see that the `"meilisearch/meilisearch-php": "^0.20.0"` is only compatible with `meilisearch 0.24.0` due to a changes in the error handler naming.
I remain available if this does not solve your problem 😊

**Comment by francoism90** [comment]
@alallema Thanks! I'll checkout if I can bump the version and it works again, closing this for now. :)
