### ISSUE TITLE
laravel scout with a where clause does not work on meilisearch-php 0.20.0 with meilisearch > 0.20.0

### ISSUE THREAD

**Issue by myneid** [meilisearch/meilisearch-php#263]
i had to pin my meilisearch to 0.20.0 as laravel scout with a where clause does not work with any meilisearch version above 0.20.0

this is what im doing with meilisearch-php 0.20.0 and meilisearch 0.20.0 to make it work

$media = Media::search($request->search, function (Indexes $meilisearch, $query, $options) {
$options['filters'] = 'gallery_id != 0';

return $meilisearch->search($query, $options);
})->get();
i did that to just make 0.20.0 work because $media = media::search($request->search)->where('gallery_id', '!=', 0)->get() only worked on meili 0.19.0
and neither work on the latest meili or anything above 0.20.0

the error i get is  with the working one with the closure is
MeiliSearch\Exceptions\ApiException
Json deserialize error: unknown field `filters`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `matches`, `filter`, `sort`, `facetsDistribution` at line 1 column 20

the error that i get with the where clause is 
MeiliSearch\Exceptions\ApiException
Attribute `gallery_id` is not filterable. Available filterable attributes are: ``.

**Comment by alallema** [comment]
Hi @myneid,
You can use:
- `laravel/scout` `v0.9.X`
- `meilisearch-php` `v0.18.X` if you use  `MeiliSearch` `v0.20.0`

We don't recommend using such an old version.

Laravel Scout is compatible with `meilisearch-php` v0.20.0 you can use:
- `laravel/scout` `v0.9.X`
- `meilisearch-php` `v0.20.0`
- `MeiliSearch` `v0.24.0`
You can check the [release changelog](https://github.com/meilisearch/meilisearch-php/releases) to see which version is compatible with each other and also [this one](https://github.com/meilisearch/meilisearch-php/issues/199) who explain why the version didn't match.

**Comment by myneid** [comment]
i am using laravel scout 9.2, meilisearch-php 0.20.0 and that does not work with where clauses with meilisearch 0.24.0. 
what i am saying is that it does nto work with where clauses with any version of meilisearch above 0.20.0

**Comment by alallema** [comment]
Hi @myneid,
Can you explain in more detail what didn't work with the `meilisearch 0.24.0`? 
If you want to use the filters you had to configure them before(https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#configuring-filters) to use it.

**Comment by myneid** [comment]
i believe that the issue lies more in the laravel scout driver. using laravel scout to import a dataset or seamlessly insert records from the models doe not add any filterable attributes and there is no simple way to add a filterable attribute with laravel scout. best suggestion is to create a whole new command for something like scout:setup which adds the filterable attributes that you want but that is not seamless at all. there should be a way from the laravel scout driver to define which columns should be filterable so that on import the index is made.

**Comment by alallema** [comment]
Laravel scout isn't made for support this kind of feature is made for search. So if you want add filterable attribute you may to do it in your Laravel code like:
```php
$client = app(EngineManager::class)->driver('meilisearch');
$index = $client->index('movies');
$index->updateFilterableAttribtues(['genres'])
```

**Comment by alallema** [comment]
Hi @myneid,
Don't hesitate to tell me if you have succeeded in solving your problem. I hope so.

**Comment by myneid** [comment]
I still believe that the scout driver should be updated to do this. 
i put a hack in there where i added a method in the model that updates the filterable attributes and then created a job which calls this method.
`public function fixMeilisearch()
	{
		$url = config('scout.meilisearch.host');
		$key = config('scout.meilisearch.key');
		$hit = new Client($url, $key);
    	$hit->index($this->searchableAs())->updateFilterableAttributes(['gallery_id']);
	}`

**Comment by alallema** [comment]
Great I close this issue
