### ISSUE TITLE
SSL Certificate problem: self signed certifcate

### ISSUE THREAD

**Issue by sourajb** [meilisearch/meilisearch-php#264]
I am using a self signed certificate for my meilisearch instance. However it meilsearch-php client doesn't want to accept it. Is there any way that we can assign a variable to enable it to accept self-signed certificates?

I keep getting SSL certificate problem: self signed certificate for https://<ip>/indexes/horses/documents?primaryKey=id

**Comment by alallema** [comment]
Hi @sourajb,
The `meilisearch-php` client does not need any special configuration and should be able to query your server with or without `SSL`. The client does not need to have certificates but it will need a key for authentication. [Cf doc](https://docs.meilisearch.com/reference/features/authentication.html#key-types).

**Comment by alallema** [comment]
Hi @sourajb,
Did you manage to solve your issue?

**Comment by sourajb** [comment]
@alallema No! Still trying to figure out where the issue is.

**Comment by alallema** [comment]
I'm sorry to hear that. But the certificate troubles are not related to this repo so I will close this issue.
For your issue, I suggest you go ask the question on our [slack community](https://slack.meilisearch.com/) where you will find the appropriate help.
