### ISSUE TITLE
Unable to authorize

### ISSUE THREAD

**Issue by danielbehrendt** [meilisearch/meilisearch-php#277]
We using the current version of MeiliSearch and meilisearch-php it seems to be impossible to connect to MeiliSearch due to a wrong header in `src/Http/Client.php`:

```
$this->headers = array_filter([
    'X-Meili-API-Key' => $this->apiKey,
]);
```

If I change this to:

```
$this->headers = array_filter([
    'Authorization' => "Bearer {$this->apiKey}"
]);
```

I'm able to connect to my MeiliSearch instance. Am I missing something?

**Environment (please complete the following information):**
- OS: macOS
- MeiliSearch version: v0.25.0
- meilisearch-php version: v0.20.0

**Comment by alallema** [comment]
Hi @danielbehrendt,
Indeed the version of MeiliSearch `v0.25.0` was released yesterday and the PHP SDK should be updated today or tomorrow at the latest.
In the meantime, the current version of this SDK is compatible with the `v0.24.0` of MeiliSearch.
Sorry for the inconvenience.

**Comment by bmpf** [comment]
Same Problem here , waiting for the update.

**Comment by alallema** [comment]
It's released! 🎉
https://github.com/meilisearch/meilisearch-php/releases/tag/v0.21.0
https://packagist.org/packages/meilisearch/meilisearch-php
