### ISSUE TITLE
Double forward slash on requests. 

### ISSUE THREAD

**Issue by Cmarenburg** [meilisearch/meilisearch-php#28]
Just curious if anyone is experiencing routes being generate with a double forward slash on requests (ending up within incoming requests to the Meilisearch server like POST //indexes//documents?primaryKey=id (taken from the console), it's resulting in 404's not found with the server, when built with the binary.
I'm not really sure where to go from here. When I generate a HTTP request via a rest client it all works fine. Anyone else have any issues? 

Can’t remember the version I’m running. Don’t have it at hand.

**Comment by curquiza** [comment]
This issue is related to the MeiliSearch core engine.

Could you open an issue on the [MeiliSearch repository](https://github.com/meilisearch/MeiliSearch/issues/new) instead? 🙂

I close this issue since it's not linked to the PHP SDKs 😉
