### ISSUE TITLE
Changelog for v0.21.0 is unclear about compatibility with MeiliSearch v0.24.0

### ISSUE THREAD

**Issue by caugner** [meilisearch/meilisearch-php#280]
The [release notes for v0.21.0](https://github.com/meilisearch/meilisearch-php/releases/tag/v0.21.0) are not really clear about whether this library version is compatible with MeiliSearch v0.24.0 or not:

> This package is only compatible with MeiliSearch v0.25.0 and later, but not with v0.24.0 and older.

But also:

> Be sure you are using at least MeiliSearch v0.24.0 or newer before doing the upgrade.

Our tests seem to be passing with meilisearch-php v0.21.0 and MeiliSearch v0.24.0, which suggests that the second statement holds.

In general, wouldn't it be possible to have each library version to always support both the current *and* the previous MeiliSearch version (here: v0.24.0 or v0.25.0), or to provide a patch release for the previous library version that adds support for the following MeiliSearch release (e.g. v0.20.1 for v0.25.0)?

**Background**: We have two deployments (stable + next) that use the same MeiliSearch service. MeiliSearch's current compatibility strategy seems to make it impossible for us to have to consecutive versions of meilisearch-php on the stable and next deployment respectively, because each version requires a different MeiliSearch version.

**Environment (please complete the following information):**
- OS: Linux
- MeiliSearch version: v0.24.0 / v0.25.0
- meilisearch-php version: v0.21.0

**Comment by curquiza** [comment]
Sorry, for the mistake, this is a typo.
The real sentence should have been
"This package is only compatible with MeiliSearch v0.25.0 and later, but not with v0.24.0 and older. Be sure you are using at least MeiliSearch v0.25.0 or newer before doing the upgrade."

**Comment by curquiza** [comment]
> Our tests seem to be passing with meilisearch-php v0.21.0 and MeiliSearch v0.24.0, which suggests that the second statement holds.

It depends on which part of the meilisearch-php library you are using. You can technically use meilisearch-php v0.21.0 with MeiliSearch v0.24.0 if you only search for example. However if you want to use the whole library, for example the task methods and the key management methods, it won't work.

**Comment by curquiza** [comment]
The unclear part has been fixed, closing this!
