### ISSUE TITLE
Integrate the package to a symphony project

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-php#30]
A user had a requirements issue when trying to install meilisearch-php for a symphony project

![annotation-2020-05-13-154107_7wnjx9](https://user-images.githubusercontent.com/20380692/81802538-8ddb4c80-9516-11ea-90f6-137cf6201b5a.jpg)

PHP version: 7.4

**Comment by shokme** [comment]
Is it possible to have access to the composer.json file ?

**Comment by jithinwds** [comment]
Please have a look into composer.json

`{
  "type": "project",
  "license": "proprietary",
  "require": {
    "php": "^7.1.3",
    "ext-ctype": "*",
    "ext-iconv": "*",
    "aws/aws-sdk-php": "^3.133",
    "beberlei/doctrineextensions": "^1.2",
    "bugsnag/bugsnag-symfony": "^1.6",
    "cboden/ratchet": "^0.4.2",
    "doctrine/doctrine-bundle": "^2.0",
    "doctrine/orm": "^2.7",
    "embed/embed": "^3.4",
    "friendsofsymfony/user-bundle": "^2.1",
    "gedmo/doctrine-extensions": "^2.4",
    "gos/web-socket-bundle": "^2.4",
    "incenteev/composer-parameter-handler": "^2.1",
    "knplabs/knp-paginator-bundle": "^5.1",
    "knplabs/knp-time-bundle": "^1.11",
    "liip/imagine-bundle": "^2.3",
    "sensio/framework-extra-bundle": "^5.5",
    "stof/doctrine-extensions-bundle": "^1.3",
    "symfony/apache-pack": "^1.0",
    "symfony/console": "4.4.*",
    "symfony/dependency-injection": "4.4.*",
    "symfony/dotenv": "4.4.*",
    "symfony/expression-language": "4.4.*",
    "symfony/flex": "^1.3.1",
    "symfony/framework-bundle": "4.4.*",
    "symfony/swiftmailer-bundle": "^3.4",
    "symfony/yaml": "4.4.*",
    "vich/uploader-bundle": "^1.13",
    "willdurand/negotiation": "^2.3"
  },
  "require-dev": {
    "symfony/web-server-bundle": "4.4.*"
  },
  "config": {
    "preferred-install": {
      "*": "dist"
    },
    "sort-packages": true
  },
  "autoload": {
    "psr-4": {
      "App\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "App\\Tests\\": "tests/"
    }
  },
  "replace": {
    "paragonie/random_compat": "2.*",
    "symfony/polyfill-ctype": "*",
    "symfony/polyfill-iconv": "*",
    "symfony/polyfill-php71": "*",
    "symfony/polyfill-php70": "*",
    "symfony/polyfill-php56": "*"
  },
  "scripts": {
    "auto-scripts": {
      "cache:clear": "symfony-cmd",
      "assets:install %PUBLIC_DIR%": "symfony-cmd"
    },
    "post-install-cmd": [
      "@auto-scripts"
    ],
    "post-update-cmd": [
      "@auto-scripts"
    ]
  },
  "conflict": {
    "symfony/symfony": "*"
  },
  "extra": {
    "symfony": {
      "allow-contrib": false,
      "require": "4.4.*"
    }
  }
}
`

**Comment by shokme** [comment]
Ok, so your problem is not related to meilisearch.
I don't know if you have post the good composer.json, but I had no issue except removing every empty `""` and escape `\` -> `\\` (App\\ and App\\Test\\)
Then I was able to require mielisearch.

I can reproduce your problem. As the error explain you have required "symfony/form" to version : ^3.0 (>=3.0 and <4.0) and you are asking composer to require version 4.4 of symfony
```
"extra": {
    "symfony": {
      "allow-contrib": false,
      "require": "4.4."
    }
  }
```
If you set symfony/form to 4.4, it should be fixed :smile:

**Comment by jithinwds** [comment]
But I have never used `symfony/form` in `composer.json`

**Comment by shokme** [comment]
Ok, I wasn't able to reproduce the error without having explicitly ask for symfony/form: ^3.0

I'm sorry, I can't help you further

**Comment by curquiza** [comment]
Wait, @jithinwds, you told me your project was in php 7.4, but i see in your `composer.json` file you use php 7.1, right? This package requires PHP ^7.2

**Comment by jithinwds** [comment]
@curquiza Yes. It will support PHP 7.2 too

**Comment by curquiza** [comment]
Does it solve the issue if you put ` "php": "^7.2,` instead of ` "php": "^7.1.3",`?

**Comment by jithinwds** [comment]
let me check it quickly

**Comment by jithinwds** [comment]
@curquiza Same error is showing after changing to `"php": "^7.2"`

**Comment by eskombro** [comment]
I have tried to reproduce the error. Symfony 4.4, took your composer.json (as @shokme, I had to remove the lines with "" and replace `\`for `/`). I'm having a different conflict. I am not a symfony user, so I don't know how deep I can go into this error. But also tried changing php version without success...

<img width="1440" alt="Screenshot 2020-05-15 at 13 21 20" src="https://user-images.githubusercontent.com/10339833/82045445-653a8a80-96af-11ea-9556-cdde06162827.png">

**Comment by jithinwds** [comment]
@eskombro I have attached my `package.json` as `.txt`. Please check it.

[package.json.txt](https://github.com/meilisearch/meilisearch-php/files/4634060/package.json.txt)

**Comment by shokme** [comment]
can you try to require another dependency like
`composer require monolog/monolog` and see if you have the same error ?

**Comment by jithinwds** [comment]
@shokme Check the screenshot. Same error for `composer require monolog/monolog`

![Annotation 2020-05-15 180027](https://user-images.githubusercontent.com/65381319/82050702-3be12500-96d6-11ea-9d57-f0c0447007fb.jpg)

**Comment by shokme** [comment]
Ok, at least this is not related to meilisearch :smile:

clean or backup your vendor directory: remove or bakcup your composer.lock and do composer install, if it works try to require meilisearch again.

if it does not work retry the same step, but add the following one:
set by hand in your composer.json require section:  `"symfony/form": "4.4.*",`

**Comment by jithinwds** [comment]
@shokme Yes. Your method works fine. Now I can install via composer. Everyone thanks for the help

**Comment by curquiza** [comment]
Glad you solved your issue @jithinwds! 😄
Thank you @shokme and @eskombro for your help on this!
I close this issue!
