### ISSUE TITLE
502 Bad Gateway 

### ISSUE THREAD

**Issue by vgavrilovikj** [meilisearch/meilisearch-php#301]
**Description**
I have `meilisearch/meilisearch-php` `^0.22.0`

When I run the following command in the terminal: 
`php artisan scout:import "App\Models\Place"`

I get 502 Bad Gateway:
![image](https://user-images.githubusercontent.com/29601489/157129963-fefdfc1a-a185-4401-95a8-b56a7a43c52b.png)

It was working, but suddenly this error started to show..

Here's how my model looks like:
![image](https://user-images.githubusercontent.com/29601489/157130401-e25fa3ae-fd15-4d61-ba02-21a5ebdba8d5.png)

**Comment by vgavrilovikj** [comment]
Would appreciate your help @alallema 🤗

**Comment by alallema** [comment]
Hi @vgavrilovikj,
Can I have the version of `Meilisearch` you are using? Also, can you try to access it with this command and check the `Meilisearch` instance runs well?
```bash
curl \
  -X GET 'http://localhost:7700/health'
```
Thanks

**Comment by vgavrilovikj** [comment]
Hi @alallema 
Here's the version that I am using: `meilisearch/meilisearch-php` `^0.22.0`

The meilisearch is set up on a digital ocean droplet and it runs on the following address: `http://167.172.188.190/`, when I go to [http://167.172.188.190/health](url) it says available

**Comment by alallema** [comment]
Sorry, it wasn't clear I edit it in the meantime. I would like to know how did you configure [this variables](https://laravel.com/docs/master/scout#meilisearch)

**Comment by vgavrilovikj** [comment]
Here are the variables config:
SCOUT_QUEUE=true
SCOUT_DRIVER=meilisearch
MEILISEARCH_HOST=http://167.172.188.190
MEILISEARCH_KEY=THIS IS THE MASTER KEY

**Comment by alallema** [comment]
Did you add a lot of data to your `Meilisearch` instance? Maybe the size of your instance is too small for your data. I'm not sure where your issue came from.

**Comment by vgavrilovikj** [comment]
No, it's not that much data - and the disk size is 25GB so definitely there isn't 20GB of data added to it. 

Me neither.. it says that there's some issue with the response body:
![image](https://user-images.githubusercontent.com/29601489/157267305-0c29beeb-e192-4551-ac8b-b293afab86b1.png)

**Comment by alallema** [comment]
You should have an invalid response you receive a `502 Bad Gateway` from the instance.

**Comment by vgavrilovikj** [comment]
How can I further check what's the issue? Because it looks like something causes the meilisearch to fail..

**Comment by alallema** [comment]
Did you have an idea when the issue started or why?
Can you provide `Meilisearch` last logs with this command (after you are connected in ssh to the DO instance):
```
systemctl status meilisearch
```
Thanks

**Comment by vgavrilovikj** [comment]
They started to appear a few days ago - not sure what happened - because that part of the code hasn't been touched for a while.

Below you can find all the logs:
`
root@meilisearch-common:~# systemctl status meilisearch
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/op

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 1
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 1
Mar 08 16:05:11 meilisearch-common meilisearch[538]: [2022-03-08T16:05:11Z INFO  actix_web::middleware::logger] 1
Mar 08 16:05:33 meilisearch-common meilisearch[538]: [2022-03-08T16:05:33Z INFO  actix_web::middleware::logger] 1
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 1
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 1
Mar 08 16:29:27 meilisearch-common meilisearch[538]: [2022-03-08T16:29:27Z INFO  actix_web::middleware::logger] 1
Mar 08 16:31:40 meilisearch-common meilisearch[538]: [2022-03-08T16:31:40Z INFO  actix_web::middleware::logger] 1
Mar 08 16:41:06 meilisearch-common meilisearch[538]: [2022-03-08T16:41:06Z INFO  actix_web::middleware::logger] 1
Mar 08 16:45:10 meilisearch-common meilisearch[538]: [2022-03-08T16:45:10Z INFO  actix_web::middleware::logger] 1
lines 1-19/19 (END)...skipping...
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 12
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 12
Mar 08 16:05:11 meilisearch-common meilisearch[538]: [2022-03-08T16:05:11Z INFO  actix_web::middleware::logger] 12
Mar 08 16:05:33 meilisearch-common meilisearch[538]: [2022-03-08T16:05:33Z INFO  actix_web::middleware::logger] 12
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 12
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 12
Mar 08 16:29:27 meilisearch-common meilisearch[538]: [2022-03-08T16:29:27Z INFO  actix_web::middleware::logger] 12
Mar 08 16:31:40 meilisearch-common meilisearch[538]: [2022-03-08T16:31:40Z INFO  actix_web::middleware::logger] 12
Mar 08 16:41:06 meilisearch-common meilisearch[538]: [2022-03-08T16:41:06Z INFO  actix_web::middleware::logger] 12
Mar 08 16:45:10 meilisearch-common meilisearch[538]: [2022-03-08T16:45:10Z INFO  actix_web::middleware::logger] 12
~
~
~
lines 1-19/19 (END)...skipping...
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127
Mar 08 16:05:11 meilisearch-common meilisearch[538]: [2022-03-08T16:05:11Z INFO  actix_web::middleware::logger] 127
Mar 08 16:05:33 meilisearch-common meilisearch[538]: [2022-03-08T16:05:33Z INFO  actix_web::middleware::logger] 127
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127
Mar 08 16:29:27 meilisearch-common meilisearch[538]: [2022-03-08T16:29:27Z INFO  actix_web::middleware::logger] 127
Mar 08 16:31:40 meilisearch-common meilisearch[538]: [2022-03-08T16:31:40Z INFO  actix_web::middleware::logger] 127
Mar 08 16:41:06 meilisearch-common meilisearch[538]: [2022-03-08T16:41:06Z INFO  actix_web::middleware::logger] 127
Mar 08 16:45:10 meilisearch-common meilisearch[538]: [2022-03-08T16:45:10Z INFO  actix_web::middleware::logger] 127
~
~
~
lines 1-19/19 (END)...skipping...
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/mei

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.
Mar 08 16:05:11 meilisearch-common meilisearch[538]: [2022-03-08T16:05:11Z INFO  actix_web::middleware::logger] 127.0.
Mar 08 16:05:33 meilisearch-common meilisearch[538]: [2022-03-08T16:05:33Z INFO  actix_web::middleware::logger] 127.0.
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.
Mar 08 16:29:27 meilisearch-common meilisearch[538]: [2022-03-08T16:29:27Z INFO  actix_web::middleware::logger] 127.0.
Mar 08 16:31:40 meilisearch-common meilisearch[538]: [2022-03-08T16:31:40Z INFO  actix_web::middleware::logger] 127.0.
Mar 08 16:41:06 meilisearch-common meilisearch[538]: [2022-03-08T16:41:06Z INFO  actix_web::middleware::logger] 127.0.
Mar 08 16:45:10 meilisearch-common meilisearch[538]: [2022-03-08T16:45:10Z INFO  actix_web::middleware::logger] 127.0.
~
~
~
lines 1-19/19 (END)...skipping...
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dump

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55038 "PO
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55040 "GE
Mar 08 16:05:11 meilisearch-common meilisearch[538]: [2022-03-08T16:05:11Z INFO  actix_web::middleware::logger] 127.0.0.1:55042 "GE
Mar 08 16:05:33 meilisearch-common meilisearch[538]: [2022-03-08T16:05:33Z INFO  actix_web::middleware::logger] 127.0.0.1:55044 "GE
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.0.1:55046 "GE
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.0.1:55048 "PO
Mar 08 16:29:27 meilisearch-common meilisearch[538]: [2022-03-08T16:29:27Z INFO  actix_web::middleware::logger] 127.0.0.1:55052 "GE
Mar 08 16:31:40 meilisearch-common meilisearch[538]: [2022-03-08T16:31:40Z INFO  actix_web::middleware::logger] 127.0.0.1:55054 "GE
Mar 08 16:41:06 meilisearch-common meilisearch[538]: [2022-03-08T16:41:06Z INFO  actix_web::middleware::logger] 127.0.0.1:55056 "HE
Mar 08 16:45:10 meilisearch-common meilisearch[538]: [2022-03-08T16:45:10Z INFO  actix_web::middleware::logger] 127.0.0.1:55058 "GE
~
~
~
lines 1-19/19 (END)...skipping...
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dumps

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55038 "POST / HTTP/1.0
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55040 "GET /.env HTTP/
Mar 08 16:05:11 meilisearch-common meilisearch[538]: [2022-03-08T16:05:11Z INFO  actix_web::middleware::logger] 127.0.0.1:55042 "GET / HTTP/1.0"
Mar 08 16:05:33 meilisearch-common meilisearch[538]: [2022-03-08T16:05:33Z INFO  actix_web::middleware::logger] 127.0.0.1:55044 "GET /admin/conf
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.0.1:55046 "GET /.env HTTP/
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.0.1:55048 "POST / HTTP/1.0
Mar 08 16:29:27 meilisearch-common meilisearch[538]: [2022-03-08T16:29:27Z INFO  actix_web::middleware::logger] 127.0.0.1:55052 "GET / HTTP/1.0"
Mar 08 16:31:40 meilisearch-common meilisearch[538]: [2022-03-08T16:31:40Z INFO  actix_web::middleware::logger] 127.0.0.1:55054 "GET / HTTP/1.0"
Mar 08 16:41:06 meilisearch-common meilisearch[538]: [2022-03-08T16:41:06Z INFO  actix_web::middleware::logger] 127.0.0.1:55056 "HEAD / HTTP/1.0
Mar 08 16:45:10 meilisearch-common meilisearch[538]: [2022-03-08T16:45:10Z INFO  actix_web::middleware::logger] 127.0.0.1:55058 "GET / HTTP/1.0"
~
~
~
lines 1-19/19 (END)...skipping...
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dumps

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55038 "POST / HTTP/1.0" 405 0 "-" "Mo
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dumps

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55038 "POST / HTTP/1.0" 405 0 "-" "Mozilla
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55040 "GET /.env HTTP/1.0" 404 0 "-" "Mozi
Mar 08 16:05:11 meilisearch-common meilisearch[538]: [2022-03-08T16:05:11Z INFO  actix_web::middleware::logger] 127.0.0.1:55042 "GET / HTTP/1.0" 200 35 "-" "Mozilla
Mar 08 16:05:33 meilisearch-common meilisearch[538]: [2022-03-08T16:05:33Z INFO  actix_web::middleware::logger] 127.0.0.1:55044 "GET /admin/config.php HTTP/1.0" 404
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.0.1:55046 "GET /.env HTTP/1.0" 404 0 "-" "Mozi
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.0.1:55048 "POST / HTTP/1.0" 405 0 "-" "Mozilla
Mar 08 16:29:27 meilisearch-common meilisearch[538]: [2022-03-08T16:29:27Z INFO  actix_web::middleware::logger] 127.0.0.1:55052 "GET / HTTP/1.0" 200 35 "-" "Mozilla
Mar 08 16:31:40 meilisearch-common meilisearch[538]: [2022-03-08T16:31:40Z INFO  actix_web::middleware::logger] 127.0.0.1:55054 "GET / HTTP/1.0" 200 35 "-" "-" 0.00
Mar 08 16:41:06 meilisearch-common meilisearch[538]: [2022-03-08T16:41:06Z INFO  actix_web::middleware::logger] 127.0.0.1:55056 "HEAD / HTTP/1.0" 405 0 "-" "Mozilla
Mar 08 16:45:10 meilisearch-common meilisearch[538]: [2022-03-08T16:45:10Z INFO  actix_web::middleware::logger] 127.0.0.1:55058 "GET / HTTP/1.0" 200 35 "-" "Mozilla
~
~
~
lines 1-19/19 (END)...skipping...
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dumps

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55038 "POST / HTTP/1.0" 405 0 "-" "Mozill
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55040 "GET /.env HTTP/1.0" 404 0 "-
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dumps

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55038 "POST / HTTP/1.0" 405 0 "-" "Mozil
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55040 "GET /.env HTTP/1.0" 404 0 "-
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dumps

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55038 "POST / HTTP/1.0" 405 0 "-" "Mozi
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dumps

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55038 "POST / HTTP/1.0" 405 0 "-" "Mo
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dumps

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55038 "POST / HTTP/1.0" 405 0 "-" "Mo
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55040 "GET /.env HTTP/1.0" 404 0 "-" 
Mar 08 16:05:11 meilisearch-common meilisearch[538]: [2022-03-08T16:05:11Z INFO  actix_web::middleware::logger] 127.0.0.1:55042 "GET / HTTP/1.0" 200 35 "-" "Mo
Mar 08 16:05:33 meilisearch-common meilisearch[538]: [2022-03-08T16:05:33Z INFO  actix_web::middleware::logger] 127.0.0.1:55044 "GET /admin/config.php HTTP/1.0
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.0.1:55046 "GET /.env HTTP/1.0" 404 0 "-" 
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.0.1:55048 "POST / HTTP/1.0" 405 0 "-" "Mo
Mar 08 16:29:27 meilisearch-common meilisearch[538]: [2022-03-08T16:29:27Z INFO  actix_web::middleware::logger] 127.0.0.1:55052 "GET / HTTP/1.0" 200 35 "-" "Mo
Mar 08 16:31:40 meilisearch-common meilisearch[538]: [2022-03-08T16:31:40Z INFO  actix_web::middleware::logger] 127.0.0.1:55054 "GET / HTTP/1.0" 200 35 "-" "-"
Mar 08 16:41:06 meilisearch-common meilisearch[538]: [2022-03-08T16:41:06Z INFO  actix_web::middleware::logger] 127.0.0.1:55056 "HEAD / HTTP/1.0" 405 0 "-" "Mo
Mar 08 16:45:10 meilisearch-common meilisearch[538]: [2022-03-08T16:45:10Z INFO  actix_web::middleware::logger] 127.0.0.1:55058 "GET / HTTP/1.0" 200 35 "-" "Mo
~
~
~
lines 1-19/19 (END)...skipping...
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-01-27 06:50:50 UTC; 1 months 9 days ago
 Main PID: 538 (meilisearch)
    Tasks: 5 (limit: 1167)
   Memory: 32.3M
   CGroup: /system.slice/meilisearch.service
           └─538 /usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env production --dumps-dir /var/opt/meilisearch/dumps

Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55038 "POST / HTTP/1.0" 405 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" 0.000454
Mar 08 15:53:58 meilisearch-common meilisearch[538]: [2022-03-08T15:53:58Z INFO  actix_web::middleware::logger] 127.0.0.1:55040 "GET /.env HTTP/1.0" 404 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" 0.000139
Mar 08 16:05:11 meilisearch-common meilisearch[538]: [2022-03-08T16:05:11Z INFO  actix_web::middleware::logger] 127.0.0.1:55042 "GET / HTTP/1.0" 200 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36" 0.000267
Mar 08 16:05:33 meilisearch-common meilisearch[538]: [2022-03-08T16:05:33Z INFO  actix_web::middleware::logger] 127.0.0.1:55044 "GET /admin/config.php HTTP/1.0" 404 0 "-" "gbrmss/7.29.0" 0.000040
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.0.1:55046 "GET /.env HTTP/1.0" 404 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" 0.000362
Mar 08 16:20:54 meilisearch-common meilisearch[538]: [2022-03-08T16:20:54Z INFO  actix_web::middleware::logger] 127.0.0.1:55048 "POST / HTTP/1.0" 405 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" 0.000177
Mar 08 16:29:27 meilisearch-common meilisearch[538]: [2022-03-08T16:29:27Z INFO  actix_web::middleware::logger] 127.0.0.1:55052 "GET / HTTP/1.0" 200 35 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 0.000378
Mar 08 16:31:40 meilisearch-common meilisearch[538]: [2022-03-08T16:31:40Z INFO  actix_web::middleware::logger] 127.0.0.1:55054 "GET / HTTP/1.0" 200 35 "-" "-" 0.000077
Mar 08 16:41:06 meilisearch-common meilisearch[538]: [2022-03-08T16:41:06Z INFO  actix_web::middleware::logger] 127.0.0.1:55056 "HEAD / HTTP/1.0" 405 0 "-" "Mozilla/5.0 (Linux; U; Android 4.4.2; en-US; HM NOTE 1W Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBr
Mar 08 16:45:10 meilisearch-common meilisearch[538]: [2022-03-08T16:45:10Z INFO  actix_web::middleware::logger] 127.0.0.1:55058 "GET / HTTP/1.0" 200 35 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" 0.000398
`

**Comment by alallema** [comment]
Thanks!
Just a new one to try:
```
journalctl --no-pager -u meilisearch.service --since="2021-08-30 14:10:10"
```

**Comment by vgavrilovikj** [comment]
Any idea what may be causing the issue..? @alallema

**Comment by alallema** [comment]
Hi @vgavrilovikj,
No, I check the log I don't know where it could come from ... You can try to change the date of this command:
```
journalctl --no-pager -u meilisearch.service --since="2021-08-30 14:10:10"
```
To see if you find something like:
```
Mar 08 17:03:36 meilisearch-v0 systemd[1]: meilisearch.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Mar 08 17:03:36 meilisearch-v0 systemd[1]: Stopping MeiliSearch...
Mar 08 17:03:36 meilisearch-v0 systemd[1]: meilisearch.service: Main process exited, code=killed, status=15/TERM
Mar 08 17:03:36 meilisearch-v0 systemd[1]: meilisearch.service: Succeeded.
Mar 08 17:03:36 meilisearch-v0 systemd[1]: Stopped MeiliSearch.
Mar 08 17:03:36 meilisearch-v0 systemd[1]: Started MeiliSearch.
Mar 08 17:03:36 meilisearch-v0 systemd[1]: Stopping MeiliSearch...
Mar 08 17:03:36 meilisearch-v0 systemd[1]: meilisearch.service: Main process exited, code=killed, status=15/TERM
```
You can also try your code on a new instance of `Meilisearch` to be sure that the problem comes from this one but I'm pretty sure it does.

**Comment by vgavrilovikj** [comment]
Okay, I will create a new instance and try it that way - thank you!

**Comment by alallema** [comment]
Don't hesitate to tell me if you find anything

**Comment by vgavrilovikj** [comment]
It works with a new instance :D

**Comment by alallema** [comment]
Great! But it didn't resolve the issue about the first one and why it finally stop working. My best guess is that you try to add too much data for the size of your instance we know that 1GB of RAM is ok for a maximum of 100Mb of dataset. Maybe you should try to increase the size of your machine on DigitalOcean.
I will close this issue because it's not related to the `PHP` `SDK`. But if you had any trouble you can ask on your [`meilisearch-slack-community`](https://slack.meilisearch.com/)
