### ISSUE TITLE
Alter composer.json `allow-plugins` section

### ISSUE THREAD

**Issue by TeddyBear06** [meilisearch/meilisearch-php#307]
Hi,

Newcomers can experience some "frictions" starting contributing as discussed here : https://github.com/meilisearch/meilisearch-php/issues/252#issuecomment-1054051683

There is still an issue regarding [phpstan using Composer 2.2.x](https://github.com/phpstan/extension-installer/pull/41/files) as `d` means `discard` not `download` and if we discard it, we cannot use phpstan:

```bash
Do you trust "phpstan/extension-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] ?
y - add package to allow-plugins in composer.json and let it run immediately
n - add package (as disallowed) to allow-plugins in composer.json to suppress further prompts
d - discard this, do not change composer.json and do not allow the plugin to run
? - print help
```

We have several options:

1. Explicity ask devs to not use Composer 2.2.x (but the [Composer backward compatibility is until July 2022](https://getcomposer.org/doc/06-config.md#allow-plugins))
2. Ask contributors to take the responsability to allow plugins and revert changes on composer.json
3. Add a [conflict section](https://getcomposer.org/doc/04-schema.md#conflict) to the composer.json:

```json
"conflict": {
  "composer/composer": "~2.2"
}
```

4. Add phpstan to the `allow-plugins` list into the composer.json like so:

```json
{
    "config": {
        "allow-plugins": {
            "phpstan/extension-installer": true
        }
    }
}
```

But honestly, I think that:

- 1 is not a good one as we cannot use brakes on updates
- 2 seems not that bad from a security perspective as it's the user who decide wich plugin to trust
- 3 is a temporary - kind of - fix
- 4 imply security considerations out of the scope of Meilisearch PHP (I mean, we need to give an explicit trust to phpstan silently (with all the respect that I've for phpstan)) but I think that it's what folks at Composer wanted

I really need your opinion on this issue.

**Comment by alallema** [comment]
Hi @TeddyBear06,
Thank you for your feedback, I agree with you I think the second solution is the best: Advice the contributors to allow composer and let them know about revert changes on composer.json

**Comment by brunoocasali** [comment]
I have the same issue in the symfony package, but adding my 2 cents:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/4116980/158807655-97cfeffe-437a-437a-860c-9ef994bde84c.png">

We have a deadline for this decision, July 2022, in other words, if I understood correctly, after this deadline we must have explicitly added PHP Stan, into this JSON object, don't we?

So why not just add `"phpstan/extension-installer": false` then?

**Comment by alallema** [comment]
@brunoocasali, if it is the case indeed it could be more efficient to add the `phpstan` line.

**Comment by TeddyBear06** [comment]
Hi @alallema @brunoocasali,

Thanks for your feedbacks.

@brunoocasali is totally right, adding the `"phpstan/extension-installer": false` line is way more efficient as it solve prompt, security implications, avoid CONTRIBUTING.md extra notes on that and avoid composer.json modification (until July 2022).

[![asciicast](https://asciinema.org/a/477801.png)](https://asciinema.org/a/477801?speed=5)

Muito obrigado @brunoocasali

**Comment by brunoocasali** [comment]
We can close this now :)
