### ISSUE TITLE
Does updateSettings() needs to be called everytime I need to sort or filter?

### ISSUE THREAD

**Issue by kiwo12345** [meilisearch/meilisearch-php#314]
I am using Meilisearch together with Laravel Scout to index my data, then instead of Scout I use meilisearch-js in my frontend to search the data.

But I have a question about sorting and filtering data, do I need to call `updateSettings` each time I need to sort data or should I simply just run this from eg a admin endpoint once to store the settings?

Because Laravel Scout has the fuction` public function toSearchableArray()` and I am not sure what this does to Meilisearch when I index my data

```
client.index('meteorites').updateSettings({
  filterableAttributes: ['mass', '_geo'],
  sortableAttributes: ['mass', '_geo']
})
```

**Comment by oluademola** [comment]
Hi @kiwo12345 👋

There will be no need to call the updateSettings every time you need to sort or filter once the sortable and filterable attributes have been defined in the settings, and when searching, all you have to do is use the [sort](https://docs.meilisearch.com/reference/api/search.html#sort) or [filter](https://docs.meilisearch.com/reference/api/search.html#filter) parameter. Regarding the toSearchableArray function, I'm not a PHP expert, but this function in Laravel allows the user to customize the data provided to Meilisearch, according to the [documentation](https://laravel.com/docs/9.x/scout#configuring-searchable-data).

Hope this helps. Thank you 🙂

**Comment by kiwo12345** [comment]
> Hi @kiwo12345 👋
> 
> There will be no need to call the updateSettings every time you need to sort or filter once the sortable and filterable attributes have been defined in the settings, and when searching, all you have to do is use the [sort](https://docs.meilisearch.com/reference/api/search.html#sort) or [filter](https://docs.meilisearch.com/reference/api/search.html#filter) parameter. Regarding the toSearchableArray function, I'm not a PHP expert, but this function in Laravel allows the user to customize the data provided to Meilisearch, according to the [documentation](https://laravel.com/docs/9.x/scout#configuring-searchable-data).
> 
> Hope this helps. Thank you 🙂

Hi @oluademola 👋 
Ok I see, thanks for the clarification :)

I just notised that my search didnt work the first time I run the query even though I set my filters/sorts right before I call my .search(); But all times after it worked so I understand it was a one-time thing

**Comment by alallema** [comment]
Thanks, @oluademola for your support! I will close this issue that seems to be resolved.
@kiwo12345 don't forget that tasks are asynchronous that's possibly why the first search doesn't work.
Don't hesitate if you have any others issues
