### ISSUE TITLE
 internal error `panic` when using php variable inside search 

### ISSUE THREAD

**Issue by Etheliene** [meilisearch/meilisearch-php#319]
**Description**
Since updating to MS 0.26 I get the following Error:
` Fatal error: Uncaught Exception: An internal error has occurred. `panic`.`
I am using this piece of code, which prior (using 0.24) has worked fine:
```
$searchContent = !empty(get_the_excerpt()) ? get_the_excerpt() : get_the_content();
$searchQuery = wp_trim_words(wp_strip_all_tags($searchContent), 10, false); // returns a string!
// Do a search
$searchResults = $client->index('my_index')->search('' . $searchQuery . '', ['filter' => ['id != ' . $id . ''], 'limit' => 3]);
```

**Expected behavior**
Return Search Results as per usual

**Current behavior**
` Fatal error: Uncaught Exception: An internal error has occurred. `panic`.`

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Meilisearch version: v.0.26
- meilisearch-php version: 0.23.1

**Comment by alallema** [comment]
Hi @Etheliene,
Thanks for raising this issue. I try to reproduce your error but I can't.
Would it be possible to have a sample of your data and research? And do you have more details about the error message?

**Comment by brunoocasali** [comment]
We need more information to reproduce this issue, feel free to reopen if this is the case :)

Thanks for using Meilisearch <3
