### ISSUE TITLE
`getKeys` returns the same `Keys` object for all keys

### ISSUE THREAD

**Issue by Nextra** [meilisearch/meilisearch-php#322]
**Description**
Calling `Client::getKeys` returns the correct number of keys but the same object for all of them, making the function unusable.

**Expected behavior**
Each Key should be a unique object containing the matching key information.

**Screenshots or Logs**
I think Laravels Tinker REPL can illustrate this quite well:

```
>>> $client = app(MeiliSearch\Client::class)
=> MeiliSearch\Client {#3921}
>>> array_slice($client->getKeys(), 0, 10)
=> [
     MeiliSearch\Endpoints\Keys {#3937},
     MeiliSearch\Endpoints\Keys {#3937},
     MeiliSearch\Endpoints\Keys {#3937},
     MeiliSearch\Endpoints\Keys {#3937},
     MeiliSearch\Endpoints\Keys {#3937},
     MeiliSearch\Endpoints\Keys {#3937},
     MeiliSearch\Endpoints\Keys {#3937},
     MeiliSearch\Endpoints\Keys {#3937},
     MeiliSearch\Endpoints\Keys {#3937},
     MeiliSearch\Endpoints\Keys {#3937},
   ]
>>> collect($client->getKeys())->count()
=> 2321
>>> collect($client->getKeys())->unique()->count()
=> 1
```

Note how every Key has object handle \#3937, sliced here for brevity. Also, since the default Admin API key is always created first in a new installation, all of these objects contain exactly that key.

**Environment (please complete the following information):**
- Meilisearch version: v0.27.0rc2
- meilisearch-php version: v0.23.1

**Comment by alallema** [comment]
Hi @Nextra,
Thanks for raising this issue and nice catch! Indeed the same Key in return multiples times.
