### ISSUE TITLE
Randomize the index name creation

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-php#334]
The idea is to promote the randomization of the test suite execution easily.

We have the same in the [Dart](https://github.com/meilisearch/meilisearch-dart/blob/main/test/utils/client.dart#L72-L74) and [Rails repositories](https://github.com/meilisearch/meilisearch-rails/blob/1aaedefa9ec3169f27574e73ee7c49ef87cff14e/spec/spec_helper.rb#L52-L57).

With this improvement we will be able to turn this: 
```php
    protected function setUp(): void
    {
        parent::setUp();
        $this->index = $this->createEmptyIndex('index');
    }
```

Into something like this:
```php
    protected function setUp(): void
    {
        parent::setUp();
        $this->index = $this->createEmptyIndex(\safeIndexName('index'));
    }
```

Becoming our test suite easier to understand, more reliable, and maintainable.

**Comment by bofalke** [comment]
Hi @brunoocasali I'd like to tackle this issue if possible
