### ISSUE TITLE
MeiliSearch\Exceptions\InvalidResponseBodyException

### ISSUE THREAD

**Issue by rainbowhat** [meilisearch/meilisearch-php#351]
Using Latest Version v0.24
use MeiliSearch\Client;

//OK
`$response = $client->createIndex('indextext', ['primaryKey' => 'id']);`

//Error
```
$response = $client->index('indextext')->updateSortableAttributes([
'item',
]);
```

Create Index in ok, but when it comes everything else like updateSortableAttributes i will get MeiliSearch\Exceptions\InvalidResponseBodyException

**Comment by brunoocasali** [comment]
@rainbowhat I still want your confirmation about the version you are using, but I strongly advise you to check the Meilisearch engine version, which will probably fix your problem!

You can check the release notes from the latest version here: https://github.com/meilisearch/meilisearch-php/releases/tag/v0.24.0.
