### ISSUE TITLE
getDocuments fatal error

### ISSUE THREAD

**Issue by vitalijm** [meilisearch/meilisearch-php#353]
**Description**
Line of code like: $client->index('movies')->getDocuments(['limit' => 2]); not returning array, but showing error:

**Expected behavior**
Return array of index items

**Current behavior**
<b>Fatal error</b>:  Uncaught TypeError: MeiliSearch\Endpoints\Indexes::getDocuments(): Argument #1 ($options) must be of type ?MeiliSearch\Contracts\DocumentsQuery, array given, called in /app/index.php on line 25 and defined in /app/vendor/meilisearch/meilisearch-php/src/Endpoints/Delegates/HandlesDocuments.php:22

When in HandlesDocuments.php I've changed:
```
    public function getDocuments(DocumentsQuery $options = null): DocumentsResults
    {
        $query = isset($options) ? $options->toArray() : [];
        $response = $this->http->get(self::PATH.'/'.$this->uid.'/documents', $query);

        return new DocumentsResults($response);
    }
```
to
```
    public function getDocuments($options): DocumentsResults
    {
        //$query = isset($options) ? $options->toArray() : [];
        $response = $this->http->get(self::PATH.'/'.$this->uid.'/documents', $options);

        return new DocumentsResults($response);
    }
```
then returns protect object with data
```
MeiliSearch\Contracts\DocumentsResults::__set_state(array(
   'data' => 
  array (
    0 => 
    array (
      'id' => 'some1',
      'title' => 'some1',
    ),
    1 => 
    array (
      'id' => 'some2',
      'title' => 'some2',
    ),
  ),
   'offset' => 0,
   'limit' => 2,
   'total' => 100,
))
```

**Environment (please complete the following information):**
- OS: DOCKER
- Meilisearch version: [v.0.28.0]
- meilisearch-php version: [v0.24.0]

**Comment by norkunas** [comment]
As the error says, you must provide DocumentsQuery instead of array.

**Comment by vitalijm** [comment]
I am trying to write php app code based on this documentation: https://docs.meilisearch.com/reference/api/documents.html#get-documents

**Comment by norkunas** [comment]
Maybe outdated docs :) try to inspect the DocumentsQuery how to set the limit and provide it, should work :)

**Comment by vitalijm** [comment]
> Maybe outdated docs :) try to inspect the DocumentsQuery how to set the limit and provide it, should work :)

Thanks. This ofcourse is possible (I think), but related to documentation for other prog languages, by logic there must passed options in simple array format.

**Comment by norkunas** [comment]
This change was made two weeks ago in #344

**Comment by vitalijm** [comment]
I'm not familiar with object oriented programming, maybe someone can give example with workable DocumentsQuery class?

But, I think someone from developers must give their opinion on current issue? Documentation is wrong, or bug in repository code or my bad ;)

**Comment by norkunas** [comment]
```
$client->index('movies')->getDocuments(
    (new DocumentsQuery())->setLimit(2)
)
```

**Comment by vitalijm** [comment]
Thanks. Works, but how access that data, writes for me:
`Fatal error: Uncaught Error: Cannot access protected property MeiliSearch\Contracts\DocumentsResults::$data in /app/index.php:28`
when trying get via $result->data

**Comment by norkunas** [comment]
$result->getResults()

**Comment by vitalijm** [comment]
> $result->getResults()

Working. Big Thank You. Ačiu ;)

Probably, currently most recent "documentation" for php client is only at address: https://github.com/meilisearch/meilisearch-php/blob/440d061fafafa4f9e61104ff0a623f9d56816593/tests/Endpoints/TasksTest.php ;)

**Comment by vitalijm** [comment]
We can close this issue, or wait for developers? Because unclear for me with docs

**Comment by brunoocasali** [comment]
Hi @vitalijm I'll check what happens in these docs, thanks for reporting this issue, and sorry for the inconvenience. 
A little explanation about this new breaking change: if we kept accepting an array of options, it would be harder to control future breaking changes because you'll not be "warned" as a user. 
In most typed languages is easier to control lib updates out-of-box but here I'm trying to apply this approach to help prevent future breakings plus helping to create a strong public API.

Thanks for helping @norkunas you rock! 💪
