### ISSUE TITLE
Support for hitsPerPage and page search parameters

### ISSUE THREAD

**Issue by lostcause** [meilisearch/meilisearch-php#412]
Meilisearch v0.30.0rc0 introduced two new search parameters, page and hitsPerPage which help with the pagination of the results. This also adds two new entries in the search response, totalHits and totalPages. This are useful for pagination, and also if someone needs to display the total number of results.
Are there any plans to add these options in meilisearch-php in the near future?

Link to the 0.30.0rc0 release notes: [https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0rc0](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0rc0)

Thank you!

**Comment by brunoocasali** [comment]
Hi @lostcause, yes, of course! 

We, the Integrations team, will be working on updating all of our SDKs before the final RC comes out, so on the day of the final release (v0.30), all of the SDKs will be ready to run Meilisearch v0.30 (or at least most of them), but you can expect the PHP will be ready on that date!

I also encourage you to give your opinion about the public API of this feature as soon as the PR comes out it will be much appreciated :)

**Comment by brunoocasali** [comment]
[Meilisearch PHP with support to v0.30 is out check it out](https://github.com/meilisearch/meilisearch-php/releases/tag/v0.26.0)
