### ISSUE TITLE
Case mismatch between loaded and declared class names: "MeiliSearch\Client" vs "Meilisearch\Client".

### ISSUE THREAD

**Issue by COil** [meilisearch/meilisearch-php#452]
When upgrading v0.26.0 => v0.26.1 , I have this error : 

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In DebugClassLoader.php line 327:
!!
!!    Case mismatch between loaded and declared class names: "MeiliSearch\Client"
!!     vs "Meilisearch\Client".
!!
!!
!!
Script @auto-scripts was called via post-update-cmd
```

I have the Symfony bundle installed. I'll try to investigate later.

**Comment by brunoocasali** [comment]
Hi @COil, thanks for reporting this issue. I'm here to help you.

First, this version is deprecated, as you can see here: https://github.com/meilisearch/meilisearch-php/releases/tag/v0.26.1

I made a mistake when I released it as a patch, not as a major/minor. And now, you can use v0.27.0, which is essentially the same code but with the correct version.

About your Symfony side, are you using [v0.10.0](https://github.com/meilisearch/meilisearch-symfony/releases/tag/v0.10.0) version? Note that there is some breaking to fix...

**Comment by brunoocasali** [comment]
Nice, I'll close this. Feel free to reopen if needed!
