### ISSUE TITLE
Swap Index method is not defined

### ISSUE THREAD

**Issue by traed** [meilisearch/meilisearch-php#462]
**Description**
The [documentation](https://docs.meilisearch.com/reference/api/indexes.html#swap-indexes) states that there should be a swap index function, yet there is none.

**Expected behavior**
A function called `swapIndexes` should exists on the client.

**Current behavior**
The function `swapIndexes` is not defined.

**Environment (please complete the following information):**
- OS: MacOS 12.5.1
- Meilisearch version: v1.0.0
- meilisearch-php version: v0.21.0

**Comment by norkunas** [comment]
It exists, see the test:

https://github.com/meilisearch/meilisearch-php/blob/11f12a2e36a6c616ffa5c6ed32272f8c870aaf69/tests/Endpoints/IndexTest.php#L254-L260

**Comment by traed** [comment]
Oh, I see. It exists in v1.0 but I got v0.21. Probably because we have some dependency on PHP 7.3 which you dropped in v0.22.
