### ISSUE TITLE
failed to set filterableAttributes

### ISSUE THREAD

**Issue by tomener** [meilisearch/meilisearch-php#478]
**Description**
Internal error will be reported regardless of whether all filterableAttributes are set or sub routes are set individually

**Expected behavior**
filterableAttributes set successfull

**Current behavior**
failed to set filterableAttributes

**Screenshots or Logs**
An unexpected crash occurred when processing the task.

**Environment (please complete the following information):**
- OS: Windows10
- Meilisearch version: 1.0.2
- meilisearch-php version: 7.4.30

**Comment by brunoocasali** [comment]
Hi @tomener!

Unfortunately, I can't help you without more information. 

Can you provide me with which method did you call? 
Did your instance have any filterable attribute previously set? 
Did Meilisearch have the same issue in previous versions of meilisearch-php or meilisearch itself, like v0.30?
Can you send me the full error from the task?

**Comment by tomener** [comment]
The problem has been resolved and needs to be set up in advance, that is, before inserting the document
