### ISSUE TITLE
finitePagination option not working

### ISSUE THREAD

**Issue by camaech** [meilisearch/meilisearch-php#492]
**Description**
When using `finitePagination = true` I get a json serialization error.

```
const searchClient = instantMeiliSearch(searchUrl, searchApiKey, {
    placeholderSearch: false,
    finitePagination: true,
});
```

**Screenshots or Logs**
`Meilisearch\Exceptions\ApiException: Json deserialize error: invalid type: null, expected usize at line 1 column 34 in file /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php on line 199
`

**Environment (please complete the following information):**
- OS: [Linux]
- Meilisearch version: v.0.28.1
- meilisearch-php version:  v1.0.0

**Comment by bidoubiwa** [comment]
Hey @camaech. What is your version of `instant-meilisearch` ?

**Comment by camaech** [comment]
Yeah I was. Upgraded to 1.0.2 and it appears to be working now.

**Comment by brunoocasali** [comment]
Thanks @bidoubiwa. I think there is nothing more to be done here!
