### ISSUE TITLE
MeiliSearch throwing "task panicked" when using geoPoint

### ISSUE THREAD

**Issue by Kyoss79** [meilisearch/meilisearch-php#535]
**Description**
Hello all, I recently upgraded from meilisearch 0.25 to 1.2,
now all my searches utilizing geoPoint are throwing a weird error.

I did change nothing to the code, just upgraded meili and the packages

**Installation**
- laravel/scout v10.2.2
- meilisearch/meilisearch-php v1.2.0
- Meilisearch is 1.2.0 (says 1.2.0 when loading localhost:7700)

**Expected behavior**
The results should be sorted.

**Current behavior**
When calling, for example:

```
curl \
  -X POST 'http://localhost:7700/indexes/jobs/search' \
  -H 'Content-type:application/json' \
  --data-binary '{ "sort": ["_geoPoint(48.85,2.29):asc"] }' 
```

meili returns
`{"message":"task 7609 panicked","code":"internal","type":"internal","link":"https://docs.meilisearch.com/errors#internal"}`     

**Screenshots or Logs**
```
Meilisearch\Exceptions\ApiException: task 7590 panicked in file /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php on line 187

#0 /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php(158): Meilisearch\Http\Client-&gt;parseResponse()
#1 /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php(96): Meilisearch\Http\Client-&gt;execute()
#2 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php(204): Meilisearch\Http\Client-&gt;post()
#3 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php(185): Meilisearch\Endpoints\Indexes-&gt;rawSearch()
#4 /var/www/html/app/Http/Controllers/SearchController.php(30): Meilisearch\Endpoints\Indexes-&gt;search()
#5 [internal function]: App\Http\Controllers\SearchController-&gt;App\Http\Controllers\{closure}()
#6 /var/www/html/vendor/laravel/scout/src/Engines/MeilisearchEngine.php(148): call_user_func()
#7 /var/www/html/vendor/laravel/scout/src/Engines/MeilisearchEngine.php(129): Laravel\Scout\Engines\MeilisearchEngine-&gt;performSearch()
#8 /var/www/html/vendor/laravel/scout/src/Builder.php(443): Laravel\Scout\Engines\MeilisearchEngine-&gt;paginate()
#9 /var/www/html/app/Http/Controllers/SearchController.php(32): Laravel\Scout\Builder-&gt;paginateRaw()
```

**Environment (please complete the following information):**
- Meilisearch version: [e.g. v.1.2.0]
- meilisearch-php version: [e.g v1.2.0
-  "guzzlehttp/guzzle": 7.7.0
- PHP Version in Docker (8.1.16)

**Comment by oluademola** [comment]
Hello @Kyoss79. Thank you for the report. I have tried making a direct call with cURL from my end, but I didn't succeed in reproducing the bug. It would be helpful if you could provide a sample of your dataset, along with your settings and any other relevant information that could assist me in reproducing the issue. Thanks in advance 🙏

**Comment by brunoocasali** [comment]
I'll close this due to inactivity, feel free to reopen if you still facing the issues!
