### ISSUE TITLE
Response compression

### ISSUE THREAD

**Issue by emanueletoffolon** [meilisearch/meilisearch-php#561]
Hi everyone.
Is there a possibility to set response compression?

I tried modifying the Meilisearch\Http\Client class by adding the following line in the constructor

`$this->headers['Accept-Encoding'] = 'gzip';`

and it seems to work fine, but I haven't found anywhere the possibility to add this header to the http client without having to change the source.

Thanks in advance and sorry if I didn't write in perfect English

**Comment by mmachatschek** [comment]
Hey @emanueletoffolon 

The client let's you pass in a custom HttpClient to achieve the desired behavior for now.

https://github.com/meilisearch/meilisearch-php/blob/c5343cc221c78c3afc1a19b71d3ceda680231c30/src/Client.php#L41

Maybe @brunoocasali has an opinion on this to make it a option to active it by default

**Comment by brunoocasali** [comment]
You're right @mmachatschek that's the way I know that this could be achieved.

If you have any issues while you try to create your own httpClient you can send a message in the discord you can get help from the community there! https://discord.gg/meilisearch

**Comment by mpskovvang** [comment]
In case others find this issue, compression can easily be enabled like this:

```php
$client = new \GuzzleHttp\Client([
    'decode_content' => 'br', // gzip, deflate
]);

return new \Meilisearch\Client($host, $key, $client);
```
