### ISSUE TITLE
[v1.4] [Prototype] User dictionary settings API

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-php#569]
**Description**
Introduction of a new setting, `wordDictionary` in Meilisearch 1.4 as a prototype. We want to create a prototype version of `meilisearch-php`, implementing the required changes to be able to try out the new settings. 

- issue: https://github.com/meilisearch/meilisearch/issues/3917
- spec: https://github.com/meilisearch/specifications/pull/255
- discussion: https://github.com/meilisearch/product/discussions/663

**To do**

- [x] GET route that fetches the setting
- [x] PUT route that updates the setting
- [x] DELETE route that resets the setting
- [x] Add tests

**Basic example**

```php
$client->index('indexName')->getWordDictionnary();
$client->index('indexName')->updateWordDictionnary(['x']);
$client->index('indexName')->resetWordDictionary();
```

**Comment by brunoocasali** [comment]
Done by #571
