### ISSUE TITLE
[v1.4] [Prototype] Separators settings api

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-php#570]
**Description**
Introduction of two new settings: `separatorTokens` and `nonSeparatorTokens` in Meilisearch 1.4 as a prototype.
We want to create a prototype version of `meilisearch-php`, implementing the required changes to be able to try out the new settings. 

- issue: https://github.com/meilisearch/meilisearch/issues/3610
- spec: https://github.com/meilisearch/specifications/pull/254

**To do**
- [x] Two GET routes that fetches the settings
- [x] Two PUT routes that updates the settings
- [x] Two Delete routes that resets the settings
- [x] Add tests

**Basic example**
```php
$client->index('indexName')->getSeparatorTokens();
$client->index('indexName')->getNonSeparatorTokens();
$client->index('indexName')->updateSeparatorTokens(['|', '/', '&sep']);
$client->index('indexName')->updateNonSeparatorTokens(['@', '#']);
$client->index('indexName')->resetSeparatorTokens();
$client->index('indexName')->resetNonSeparatorTokens();
```

**Comment by brunoocasali** [comment]
Done by #572
