### ISSUE TITLE
Cannot update ranking rules on index

### ISSUE THREAD

**Issue by Murkrow02** [meilisearch/meilisearch-php#593]
**Description**
I cannot update ranking rules with proper method

**Expected behavior**
Ranking rules are updated as expected

**Current behavior**
 Meilisearch\Exceptions\InvalidResponseBodyException is thrown

**Screenshots or Logs**
![image](https://github.com/meilisearch/meilisearch-php/assets/38087157/0255932e-38d0-4fe4-83f6-24b7115dca82)

**Environment (please complete the following information):**
- OS: Ubuntu Linux
- meilisearch-php version: 1.4.0

**Comment by Murkrow02** [comment]
The problem seems to be that the php wrapper uses "PUT" while the endpoint wants "POST"

**Comment by norkunas** [comment]
Please include error from response

**Comment by Murkrow02** [comment]
![image](https://github.com/meilisearch/meilisearch-php/assets/38087157/565ede6c-982b-4cec-9b00-59a620841255)

**Comment by norkunas** [comment]
Not sure for now,but there are integration tests that works :)

**Comment by Murkrow02** [comment]
My bad, docker compose was using an old version :(

**Comment by norkunas** [comment]
Glad you worked it out 😉
