### ISSUE TITLE
Installation error on updating from vs 0.10 to 0.11 or 0.12 using composer

### ISSUE THREAD

**Issue by Sediug** [meilisearch/meilisearch-php#63]
Good morning!

I'm trying to update the lib to the new versions but I'm having a problem while trying to do so. Aparently there is some dependency conflic between your dependencies. I don't use either `php-http/guzzle6-adapter` nor `php-http/httplug`. It looks like your library requires `guzzle6-adapter` in the version ^2.0 and also the this library requires `php-http/httplug`. It has some conflic doing so. I don't use any of those libraries in my composer file.

```sh
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for meilisearch/meilisearch-php ^0.12.0 -> satisfiable by meilisearch/meilisearch-php[v0.12.0].
    - Conclusion: remove php-http/httplug v1.1.0
    - Conclusion: don't install php-http/httplug v1.1.0
    - meilisearch/meilisearch-php v0.12.0 requires php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].
    - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[2.1.0, v2.0.0].
    - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[2.1.0, v2.0.0].
    - Can only install one of: php-http/httplug[2.1.0, v1.1.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - Installation request for php-http/httplug (locked at v1.1.0) -> satisfiable by php-http/httplug[v1.1.0].
```

Have you any idea of how to solve this problem?

I've already tried to remove vendor and package.lock and reinstall everything again but the problem keeps happening.

This is my composer.json file dependencies:

```json
"config": {
		"platform": {
			"php": "7.2"
		},
		"process-timeout":10000
	},
	"require": {
		"lusitanian/oauth": "~0.8.9",
		"ircmaxell/password-compat": "~1.0.4",
		"kriswallsmith/assetic": "~1.3.2",
		"patchwork/jsqueeze": "~2.0.3",
		"onelogin/php-saml": "3.1.1",
		"phpoffice/phpword": "^0.17.0",
		"dompdf/dompdf": "~0.6.2",
		"ezyang/htmlpurifier": "~4.7.0",
		"mailgun/mailgun-php": "^2.1",
		"jakezatecky/array_group_by": "~1.0.0",
		"vlucas/phpdotenv": "^2.2",
		"gregwar/image": "^2.0",
		"bjeavons/zxcvbn-php": "^0.1.4",
		"greenlion/php-sql-parser": "^4.3.0",
		"marcj/topsort": "1.0.0",
		"websharks/js-minifier": "150511",
		"ramsey/uuid": "^2.9",
		"symfony/expression-language": "^2.8",
		"nodejs-php-fallback/uglify": "^1.0",
		"predis/predis": "^1.1",
		"leafo/scssphp": "^0.4.0",
		"league/flysystem": "^1.0.35",
		"aws/aws-sdk-php": "^3.74",
		"league/flysystem-aws-s3-v3": "^1.0",
		"illuminate/support": "5.2.*",
		"illuminate/database": "5.2.*",
		"illuminate/container": "5.2.*",
		"illuminate/pipeline": "5.2.*",
		"filp/whoops": "^2.1",
		"guzzlehttp/guzzle": "^6.2",
		"guzzlehttp/psr7": "^1.3",
		"daniel-zahariev/php-aws-ses": "^0.8.8",
		"illuminate/redis": "5.2.*",
		"monolog/monolog": "^1.22",
		"maxbanton/cwh": "^0.3.0",
		"league/flysystem-ziparchive": "^1.0",
		"kettle/dynamodb-orm": "^0.2.8",
		"league/csv": "^8.2",
		"doctrine/dbal": "2.9.3",
		"google/cloud-vision": "^0.6.0",
		"ddeboer/transcoder": "^1.0",
		"neitanod/forceutf8": "^2.0.4",
		"box/spout": "^2.7",
		"php-ds/php-ds": "^1.2",
		"firebase/php-jwt": "^4.0.0",
		"thenetworg/oauth2-azure": "^1.3",
		"sonata-project/google-authenticator": "^2.0",
		"fzaninotto/faker": "^1.6",
		"mockery/mockery": "^0.9.7",
		"friendsofphp/php-cs-fixer": "^2.3",
		"phpmd/phpmd" : "^2.6.0",
		"mobiledetect/mobiledetectlib": "^2.8",
		"symfony/lock": "^4.2",
		"justinrainbow/json-schema": "^5.2",
		"symfony/http-foundation": "^4.3",
		"CBIConsulting/laravel-cte": "1.2.122",
		"nilportugues/sql-query-formatter": "^1.2",
		"eluceo/ical": "^0.16.0",
		"spatie/calendar-links": "^1.2",
		"meilisearch/meilisearch-php": "0.10.1"
	},
```

Thanks for your time. I will keep using the versión 0.10.1 instead and dowgrading my meilisearch server while we can not solve this problem.

We're in a development phase, adding meilisearch to our project so I think it'll be the time to upgrade the lib and server version.

**Comment by curquiza** [comment]
Hello @Sediug!

That's weird, we indeed changed the dependencies between the `v0.10.1` and the `v0.10.2` (see this PR https://github.com/meilisearch/meilisearch-php/pull/16) but you should not have any problems.

All our tools using `meilisearch-php` (e.g. [meilisearch-laravel-scout](https://github.com/meilisearch/meilisearch-laravel-scout) and [meilisearch-symfony](https://github.com/meilisearch/meilisearch-symfony/)) suceeded to upgrade the `meilisearch-php` version each time it was needed without any dependencies issues.

> I don't use either php-http/guzzle6-adapter nor php-http/httplug

Are you sure any of your dependencies do not require `php-http/httplug`? Because I tried your `composer.json` by removing the `meilisearch-php` line and I found that `php-http/httplug` is still present in the `composer.lock` (FYI I also had to remove the `CBIConsulting/laravel-cte` because I got an error).
Indeed `php-http/httplug` is a required dependency of `php-http/client-common` that is itself a dependency of `mailgun/mailgun-php`.

**Comment by Sediug** [comment]
@curquiza Thanks for your time, I'm gonna check that and get back with more info.

**Comment by Sediug** [comment]
@curquiza Thank you very much! It's working properly! It's that, an old dependency someone added for a reason I don't yet know, we don't use it. You can close it!

**Comment by curquiza** [comment]
@Sediug! Glad you solved the issue! 😄 Closing...
