### ISSUE TITLE
Integration tests against rc are outdated

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-php#665]
Our [pre-release tests](https://www.notion.so/meilisearch/Roles-missions-of-the-team-members-2dac12d75c2f420487e1a813b792e364) are outdated compared to our ["classic" tests](https://github.com/meilisearch/meilisearch-php/blob/main/.github/workflows/tests.yml)

We made changes here but we did not apply them to pre-release tests: https://github.com/meilisearch/meilisearch-php/pull/651

To let you know @norkunas

**Comment by norkunas** [comment]
Yeah, I saw that. Totally missed this 😓

**Comment by curquiza** [comment]
Don't worry, it's definitely not a big problem 😄

**Comment by curquiza** [comment]
Fixed by #666
