### ISSUE TITLE
Missing support for rankingScoreThreshold in SimilarDocumentsQuery

### ISSUE THREAD

**Issue by andrefrcastro** [meilisearch/meilisearch-php#671]
The `SimilarDocumentsQuery` class in the Meilisearch PHP SDK does not currently support setting a `rankingScoreThreshold`, which is documented as a feature. Attempts to set this parameter through the constructor or via a method are ignored, leading to inconsistent behavior compared to the API documentation.

Steps to Reproduce:

1. Create a SimilarDocumentsQuery object.
2. Attempt to set rankingScoreThreshold.
3. Execute searchSimilarDocuments.
4. Observe that the threshold is not applied.

**Comment by norkunas** [comment]
Thanks, I've submitted a PR #675 to fix this
