### ISSUE TITLE
Documentation Error: Incorrect Method Name getSimilar() Instead of searchSimilarDocuments()

### ISSUE THREAD

**Issue by andrefrcastro** [meilisearch/meilisearch-php#672]
**Description**
The documentation for the Meilisearch PHP SDK incorrectly refers to the method `getSimilar()` for retrieving similar documents. The correct method name is `searchSimilarDocuments()`.

**Expected behavior**
The documentation should accurately reflect the method name `searchSimilarDocuments()`.

**Current behavior**
The documentation incorrectly uses `getSimilar()`, leading to confusion.

**Screenshots or Logs**
<img width="581" alt="image" src="https://github.com/user-attachments/assets/411d58ba-bc06-4382-b2ca-39f47c9df8fd">

**Comment by norkunas** [comment]
Hi, thank you and sorry for this confusion.
I've submitted PR #673 to fix this
