### ISSUE TITLE
[Search] FacedFilters documentation

### ISSUE THREAD

**Issue by Guikingone** [meilisearch/meilisearch-php#69]
Hi everyone 👋 

While working on a separate Symfony bundle that wrap this SDK, I'm facing a strange behaviour/situation, I'm trying to build a `Search` class which allows to build complex queries and ease the search process.

The issue is when I'm trying to build `facetFilters`, I've looked at the internals of search and it seems that the request wait for a specific array: 

```php
// Index::parseOptions()

    private function parseOptions(array $options)
    {
        foreach ($options as $key => $value) {
            if ('facetsDistribution' === $key || 'facetFilters' === $key) {
                $options[$key] = json_encode($value);
            } elseif (is_array($value)) {
                $options[$key] = implode(',', $value);
            }
        }

        return $options;
    }
```

The issue here is that the documentation of this SDK does not explain this type of search and/or the type of body required to be encoded, is there any internal documentation about it? 🤔 

Thanks for the feedback and have a great day 🙂

**Comment by devrck** [comment]
How I see this SDK is a soft wrapper around the REST endpoints so the documentation for the REST endpoints is good enough.

**Comment by curquiza** [comment]
Hello @Guikingone!

This part might (not 100% sure) be removed: the `search` method in this SDK will only use the `POST /indexes/:uid/search` route (and not he `GET` anymore) for performance reasons.

See:
- #66 
- https://github.com/meilisearch/MeiliSearch/issues/866 => I wait for the answer before starting any detailed documentation about the search route and its parameters.

I let this issue open for the moment, then! 🙂

**Comment by Guikingone** [comment]
Hi @curquiza 👋 

Thanks for the feedback, good, even if the `POST` method is used, the facetFilters will stay isn't it? 

It could be a body key/value 🤔

**Comment by curquiza** [comment]
> Thanks for the feedback, good, even if the `POST` method is used, the facetFilters will stay isn't it?

Of course, they are still available 🙂 

> It could be a body key/value 🤔

As a basic version, the package is just a simple wrapper around MeiliSearch: I mean, the expected syntax would be the same as the expected syntax in MeiliSearch, but we can think about a more user-friendly way to handle it 🙂

**Comment by curquiza** [comment]
I close this issue since we have now:
- only the POST method is now used in this SDK: the required type is now an array and not a single string.
- documentation for PHP in the main docs, in advanced guides (see [Search Parameters](https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html) section of example) and in the API references (see the [search route](https://docs.meilisearch.com/references/search.html#search))

Feel free to re-open it if something is still not clear 🙂
