### ISSUE TITLE
Placeholder Search

### ISSUE THREAD

**Issue by arkste** [meilisearch/meilisearch-php#78]
According to the [Documentation](https://docs.meilisearch.com/guides/main_concepts/search.html#placeholder-search) it is possible to ommit the query parameter.

Looking at [Indexes.php](https://github.com/meilisearch/meilisearch-php/blob/master/src/Endpoints/Indexes.php#L120), it seems there's no way to run a search without the query parameter currently.

There should be a way to run a "search" without the query parameter, but with filters for example.

**Comment by curquiza** [comment]
Hello @arkste!

You can do it by wirtting:
```php
$search = $index->search(null);
print_r($search)
```
And, of course, if you want the facets:
```php
$search = $index->search(null, [ facetsDistribution: [ ... ] ]);
```

This is currently not intuitive, but in the future version of MeiliSearch you will be able to write:
```php
$search = $index->search('', [ facetsDistribution: [ ... ] ]);
```
which could be more convenient in some front-end use cases 🙂

Hope I'm clear, feel free to ask any question! And thanks for using MeiliSearch 😁

**Comment by arkste** [comment]
Thanks for your quick response, @curquiza !

I've tracked down my problem, it seems the problem is in the [meilisearch-symfony/Engine.php#L156](https://github.com/meilisearch/meilisearch-symfony/blob/master/src/Engine.php#L156) package, which passes always a string to the search api and never a `null` value. 

This might be ok, once MeiliSearch will accept an empty string in the future.

I will close this issue, since its not related to this package.

**Comment by curquiza** [comment]
Thanks for the investigation @arkste!
I'm going to do a quick fix anyway because the version of MeiliSearch containing this change will be in a few weeks, but I don't know when exactly!
