### ISSUE TITLE
Delete index method should return array

### ISSUE THREAD

**Issue by emulienfou** [meilisearch/meilisearch-php#79]
In the endpoint class `Indexes`, the method `delete()` seems to return `void`:
https://github.com/meilisearch/meilisearch-php/blob/dc506d60be544b996558f64d20d7c70ca8278810/src/Endpoints/Indexes.php#L80

However, the HTTP `Client` method `delete` seems to return the value of the executed query:
https://github.com/meilisearch/meilisearch-php/blob/dc506d60be544b996558f64d20d7c70ca8278810/src/Http/Client.php#L150

Related to Symfony bundle too, the bundle will probably return an error when trying to delete an entry, because is seems to return an `array` in the next line: 
https://github.com/meilisearch/meilisearch-symfony/blob/3714b3cbb1a5c9a7e8a57b289e197f548b532cc7/src/Engine.php#L140

So we need to decide if we return `void` from the beginning to the end or an `array`.   
From my perspective, I would prefer to return an `array` with the response if the index has been deleted correctly or not.

**Comment by curquiza** [comment]
Hello @emulienfou!
Thanks for your report!
@ppshobi if you are around, what do you think about this decision? 🙂 It looks like we added the `void` during the refactor we merged https://github.com/meilisearch/meilisearch-php/pull/43/files.

**Comment by ppshobi** [comment]
The `DELETE` request may or may not have a body in the response. But usually the response code for a delete request is a `204` no content (which does indicate that there is no body inside the response), So it makes sense to have a void return for delete response. 

But here I'm not sure if Meilisearch returns a body for `DELETE` requests. Anyways if it aids the developer friendliness, we can make it array, I guess.

**Comment by ppshobi** [comment]
I think it's better we make it array. So even in the future if Meilisearch returns some body for delete requests, we don't have to worry.

**Comment by curquiza** [comment]
> But here I'm not sure if Meilisearch returns a body for DELETE requests.

It indeed never returns a body so far

> So even in the future if Meilisearch returns some body for delete requests, we don't have to worry.

I like this idea!

Let's start with the `array` return then! 🚀
