### ISSUE TITLE
Syntax error in HTTPRequest class

### ISSUE THREAD

**Issue by szwagros** [meilisearch/meilisearch-php#8]
There is not needed, extra comma at line 34 in HTTPRequest class resulting in syntax error.

**Comment by curquiza** [comment]
Hello!
What kind of error do you get exactly? Can you send the error output and the steps to get it? :)

**Comment by szwagros** [comment]
Hi!
It's syntax error:

PHP error: syntax error, unexpected ')' in /home/vagrant/code/hash/vendor/meilisearch/meilisearch-php/src/HTTPRequest.php on line 35

Steps to reproduce - just install and try to instantiate client class e.g.:

composer require meilisearch/meilisearch-php

and then just :

`$client = new MeiliSearch\Client('http://127.0.0.1:7700', '');`

**Comment by curquiza** [comment]
Thanks for the details.

Unfortunately, I did not succeed to reproduce your error.

My steps:

```bash
$ composer require meilisearch/meilisearch-php
```

then, in `test.php`:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$client = new MeiliSearch\Client('http://127.0.0.1:7700', '');
```

```bash
$ php --version
PHP 7.3.11 (cli) (built: Feb 29 2020 02:50:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
$ php test.php
```
And it exits with no error.

What is the version of your php?

**Comment by szwagros** [comment]
Mine is 7.2 

```
php -v
PHP 7.2.20-2+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jul 25 2019 11:42:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.20-2+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.22.0~linux-x64-non_zts72, https://blackfire.io, by Blackfire



```

**Comment by curquiza** [comment]
Indeed! it came from the version. I succeeded to reproduce the error with your php version. I didn't know that this kind of change could exist between two unbreaking versions.
I'm going to fix that.
